import React, { useState, useEffect, useMemo } from "react";
// ---- CONFIG ----------------------------------------------------------
// Default WhatsApp number ‚Äî editable anytime from Staff > Settings, no
code changes needed.
const DEFAULT_WHATSAPP_NUMBER = "61416379260"; // country code + number,
no + or spaces
// TODO: change this to whatever code you want staff to use to open the
order list.
const STAFF_PIN = "1974";
// TODO: paste your Google Apps Script Web App URL here once deployed
(see setup guide provided separately).
const SHEET_WEBHOOK_URL =
"https://script.google.com/macros/s/AKfycbzkxHFUZx3i8U-
2Weg57ouiVr7fngOsvKlztEFl1wbD_33FG_G8HxC3t9Mk2LJq8MSCwQ/exec";
// Official logo, extracted from the Dog's Station menu.
const LOGO_URL =
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPkAAACDCAYAAABP9r03AABj/k
lEQVR4nO2953YsuY6g+4EMk1Zuu6rTM3Pn/d9qVvd01fZyacKQuD/IcJmRTtKuOt1zoCUpTQQ
JMghLABRV5f8N0PhX4tvwXvqfNSDsfvIv+Bf8lwX5r0jkGgkW7YhxfxQSPz18xXnQsQGVpk2Q
pn2V3mUNQv9iEf+Cfx745yXyiJe+lkb/BhD5F5H/C/554J+MyJV/KnTeEqT/8l9M4F/w10Hyd
yPwctAg7dXH115RH1T5AacQEAmEJdK8F/rvIb6GX6pqa++FgKr8y/7/J4bWLIxP6L/qc/onIn
I9QyVX8A58pepr8BV4h6iPBK8css4bIlYEEdHw3qBiQCwiBoyB+B4xEl73GMErh7f/UnfM+v+
qy+i/I+jO6/+6z+afiMiP0bgHV6nWBbgCXI3gR4la9l7p4N/u9zJ4Gwg6EL6oiAVjUZMgJgGT
RMI3vPqh7w72v/Y6+hf8E8PfbpPrUQmuQWqXa6TeBCk+Qg2dzxuQIVHvGMP7t+vei/374lvFQ
iB2sA3hWxArb0L4e13/S7b/faB74uO/6rP424g8dHukb19DtQoErq5/Z/jXbFnhg12u45K9g8
YGB+ip4a063vzq4JajJoQIKjao+yZBbQo2RUz6IqIf7273U+FfzvszQHeJ9O+Dv3u35W8h8kD
fB/pVD65QLZ7BFcjA+RGJWD1ojWrd2eMXQ+Px6ohdxSA06rhh1BnXWgH7JKkIiIn2fSB6sVkn
7XedfS8FOUOqnFBM/rtCE/J0PoX/BXaS/L16wN9D5IekuK+gXCvVGrSm83xHwvZ1+Fyj2j50f
r4BYk17PckeHXSI7BB/n1iPiPzWkWfBBnVfTYJIAsYIYl82gJZB9YNzekMZfa5NCI/uv99lXm
+95XcJLe1sjnRulThW6Vh/N5RdM+01sOPEbeayYfovNM3+Lon+lxP5vg0eeW9dKOUT4oqeZBb
ARy96FV7/KuLu0+mY7d5+0SN+MYBl6IVvXjd47iDbaAxigqpv0mDb2wSMvYzoezjvrp9/hniD
xrXZBhQfiwbUHrPZs5j+AmkbhIjia9S7KEw8or3eRaK2ZhEbnh2taXY+9Hd7/gr4pyByrTbK9
gFwSJ/AtQ7edBqHW3tLe0n7/q9mkntSn47oTUP4keNrD0Fpxr/r2ItEb7Ng19s0evPtRWg1a+
efgcghaAEBFR8JVvbNjYbA+x+09/eJ/CUP+ZhjJTh2qbdoXYKrwq7NHoPebS/8U2x4VkkOyVQ
wCfuL8wBW/x2JvOum35+PBP6IaD28wZeo79vk58PYY9377FcwhoGaKXQEb3sq3s5i3SN6D0SH
ngnqfSD4tLeFFzWG/0fhlD90CCPbKd4Fv0+9hbpAvDugtTX3777vv9bAuGwG6RxJpyOMeUxVf
AVItE7OZBS/nMiHTra+geXR8lkpn4PzrJ0Ih7oS0You4eM0HLrshS65V7XRjnKP6AfBNoza9y
3R77QYzQM1FiRs3YV9/F7wTt+x91dE8P1KuIySD0C0rYOjVtVVEH8lquNdZ+x0qN39A7z6z2t
4n4qAyZBsAUl+sRZ2MUhnEh297FcS+cE98JbAn6J6HonZe/DbaA+xr9G27Y5/Po7DPpxLxKfI
4xRfPjyzu7Z9n+j7Tp0jmPYWm4oEj37vV3vMpPtOuq29t4rk+6eChqgdqAtRka6JjKxBtSdQY
Fcih/t8/K/d5wPoP7P4u0PwaiwkMyRbRBX+FXCI2Un/399A5McDXDxarpTioXWINhOsbovg9g
j8NUvxNaN7LQmM9j3KGXpE3Ur8Hbt+zyY9xZoaNt/zF7TEb3rELzvfCYKRfY1gD+k3h/OFd0P
MCjjFR8L0jhDu7EJsRRM/sasut/So7X3gumv7NDHGZxu/Bw1zTYI5haURWIqFZIrkyyOEvi/J
LlJgpOlOjj6atydyBR1VOaNKU66U4nEY4NI42HTMNjpP8h6S8q+Fc5b1QCsf++7F9n9DaD0pP
7Dv4zX7Xqz9Zg5OTCBkbQm6z2gaBiBdn51WEBY49EyFprMxvM7Qd/o2TiNJ1SuqaBvwFInR94
hYNQqHI0+/9UiGe1RdUNm9B/Hj94w92D3Ls8dEbR6IPTpaVQTSGTK5lqM+FO/BedR7FWMEG/M
oBoicXkCHiP3VRL7rTxMORRopWq2DBPe+u2ngQR+HV9nIAyZ+LqWd7wu4CIdD74/dtwu9qL2w
Fde39XftxbFO+hNy2cx2d4S/2hJ1s9A73I4T/G7DO4SN9rau+pL11JPvc7M+VfYI2ze2+Ilnf
K6PbDCdgpoMMfkAJ82XSH4VfMiq4D1aVqrFFt0WUBRIXYNXxBh8kkCeYWYzZDaVsL163oIc26
Z8IZGHvG+RMSI/8CjqrWrxgLiy14wDt92X4Kfs8bOIpr/4Ldpkmh1acE0YZJe6GhdYX4Xr2Wj
aG/C5cFLkn9neUeIfkcYDG7z/+hAynPju1/lxDoOMLK5dPPrPpi/pfXzfNTV226g1dERdHwNF
wOSISQMX9KBqUDtDKo+WJVqWSFUjru7opiVObZUxNQJZDrMZMp8hkzwQ/IH+Zfin+/wSItfhn
/PB1+j2p0pd0M2SAxeTTs5Y2AeZx97DaKLKshBk0tq1l2w57RDzXox8WDSNCtmF1r6A8C+A3T
kYNVEO2jJjTADYZQADtbsvofv3j/TeK421by5I3PIZfnzAotvHfbBGe8xWe//bZxT/t9fs93s
xnNWGtEsEb8Cn4ARqDy4KRa9hHi7CKWzRaZoEYl8ukNlMhup8X5nYb/hCIh+ztU/d5NHtvUq1
6qHj0XqDUDcNHx307mJuLx+o4gZNcsROQJIRafWW0JfsHeFrL/RWdMdGPKY5H4FzBftBJti/6
GSjY9K999motjCmko8whaMD2V1XuwEpu6/7K0H32zghkce+Ps09d8cgHTo1UAlUgBfEC2jQzu
XoQxlv/tAtKgKJRRdz5PYWybLBjGt8sRuGfBmRX6zaa9gq2z4gvYehbov4qsPuCIw+kJ0P1OR
IMgObjjR4cvm/EA6120gWh2rYvhHvUHWA70X0jaB6oJdz4Swi76+k1zQ+OvxDDR4wkXYbPiba
X8KvDzC2o8S0yzH7ZKSgXoL7qCIQtiNIbBrievl6O7rWd77T6RT58B6ZTUYmN+LT8NeThKtRg
p/oNEjWoYqr9TZulTnawfsy/KLH2dwhm6j3nZoE7AxJJgwdBP8M0JNg3d5tMF20Bt9k0J3hBD
qjp1cP/VQDb6AU/Sp2ewnDOmjiDChMOmQdaC1ILUFi19IqGqe2rvaRHMOga2Cc+ewh1651n6b
w/h3majmaf9wk8hwk8n7Z46PgPVrVSlWhVYWWJcY5cA51FeJ6hR4kqreiwUQ22uZ30PzKOcQv
qM2QZB73JwdDOwPpvwv6dmuj5tfD7Drt2ZP/DeFcafWXQqPnapDM6ghSuiZIad9I6XO4ycj6k
928v14zvd27U+r6GARCv8NcXx3kOIeJ/JiEVw2Evd2imw1st1BV4Dp1VPoTsse0tPvbME1LJH
pFbHwvICYyhNbEM2gyQZJpsL1b2/hX2d+XwrlMZue6xiPs66Daqwsx1U1abWMG/LMM84XwJkT
+6scdpbEP6rdEad0SdZzu16XYathizICJD3EyTtASpIqFRb2CPyXJT4NLE+TjB8xyOYrwOJEf
q6rhPLp6Vn14QrZbcG5I0C+GPidQtA300k7KGyBNIJ2G3GxrwEiMxdjtf9eZ81fD7nJukOl7R
T2H563vzY82vW8cemc49fpdn7rmDOxPXXPq2rHr3/TxjDW2Y0/jJPDMhpgdgcg8oK/Nmu8xYB
FUFJ0qslQki+JaBa0EfRTMRnoEHujnNQzQpQnmH78j0+neMPaJvDnUYKylusZ9+6by+IzxTfD
KW4uWMUmovVfxewE1BjUGrIQya0kCSST+xCCRCQwcP4PAi7eGBnclrqR46krvO3XxcSZAunPP
qMdnBzoPvrrGtq/Zm7NXEv4/m8Kg7R/GRV4fYekRdS1QKlqDuOj53rth0MuR73euk/hHYp9xf
0wN6NQjC0WSEE0oTbCXgG4tfAZRO+jz1Jyf8oy5xQLz2yeRZBhG2xH5qZpYzuM/f1Z5fOzxnJ
cqGK+FvuagHWOKaHghSngDNhJ7YlHbe28lll+XLppI4OVjiuq2VIERmSxkiYmNTRoaIsdXqG4
JATcJaBP3PFipR/BomFYcu69bNT9EdLnoU9GoZf09Ks2vWh3D7FxplTbx0qndFWitiDOd11t2
ibj//lzOF9deo5DJsB0Vj58qmnns1EI6DzssumnbUGfQz2AK21tzeyfy7cGpeVRr0I8f9uzzj
uSPmZLe4759VfP4NGKnDCX/4FuJnsBB2yNq9KBe2jkyxAyvj9JSjIAqtkGo9uGXHltouK6Jsc
VGgjZgwmuxMUrM9hhA739zLkPHxR1ISZDaBmQSgnDasVZ0KY1NMsMEYQK6Rf0aYQtkoBnhkZy
y6/tzGBgKJo0zF2O5YxhnF7wTPtf4ej9cVIeP4NDjGPv8yLXa/3zMqrukvfbroOpqzCsJQSe0
TjIURGUnVGIoMfdFmoy8jQj32xkzC/v/Ew2/EJ6zzEB/DC8fTMoQt1eB8/C8gvkcetK8e3WkH
79aqdw/jMy5EkwcDwppc1IJRFu6x1D69tGgv0aTkBHGquFH6CrsKKgKoopor9QS7KvgvQfSZw
tB6CqNa3NvutsNxoC/RokvkTGoATJB5oIkJeBRyUAsQgluTRAlu55yQYl54JIFhmCXqHtGdA2
yBSagOd2j2SX44+ZMGzcuFiEdXqNRsg9CdRvid7S17NWj0sSPN/fENpoF31/43VTuY9WgOyC4
E8NpPm9eRCVJGzu6JWhpN2vYPY3miKw4uNQHxBz/DNo5zn0UUBuHaxLEzuMtvbyMZrxOz5NnO
+gdYwcCaFGgZamSJG3rJ5NddbNRvv/E7FQn9UCBp1SPRZhIoxY1Pe5O0KDVfdW4R5CqGrTXTC
FLkTQJNjYe9RVSu0BDpQ/eyjo8nWNzNj450v5t9BFpFlVAJH7faSuaeJiBTIHERyIQRAtUC7q
QynFoU2l1C6xApoiZoN4h7Wcl6IzgmmVk5e487rMEQafxjBUzkH5DLTPQSPgeqFHdIsaDTVFJ
Qy5AV5Qh5G7XvmXYgVGcgeOIANC6IehdKX3gOV9IMIOp3BNEDcK7jY510udgGnaIAMkmIBPUP
4c57EMF4t66sk/AQyoHRQnTafu8jxN5XaM/75FtMfjYARt1FHgmGKZiLyxGtKsPduqiGkXnBC
mZz8EuI5qGoGY68BtUn4LTqQLdKqwNFIr4vnTffVD7D27/3b7kVPWoUWRB9JbuqLdR1Fy2zhS
oQZ/AR/u9ZaQliEPLFP9kMGLBduYFYmLuTSTcqGV0qmXDYMdUUPY1nr42Bd38SdR/pAhEbFIw
i8CYBgUnI5HbDZo8hx0XzUEt3dl0wyzDRhtW1RARWPtAzC1RE0JEm8CUUaK7YKqbNvpqd18j0
d0bzm2430fcFbIWSZdxgBt215MvCELzBcPpK0+j36iHsqmqtEPkezepos8rldUqcqIwG4pS4C
jxTLDMjB2GajbgG7vkOJGFj01QyzOPXIPJFewczBVh+2gdkJeAskiOIKg8IFmFZAILjxagKw8
FcYE0SrpG6TJQ2g9MVoNj+MYbB1OQK+JWiJ6/Bs4FLWGvjrtDMoeZWvxPxVSmS4mOxKyE56hN
ZFPrawhfaONn6PsUeoxh+J5olgSdSAGMQ2QDFKidI2YZp6ZC/QZiTYDW/LCLoKKaB/AFQkYwP
eLQmkQS59HaoVWNljWmEnAm0GCj4+9J1/66GVvqu2srbGMhilpFEoJ22CwBr6hXcIJ44loRQm
75KZ2weRCmHZMq6FTxFpLpItTb96vwbPt31xKUuLGMnQvgMLEHv0tPLw5EPrpVXlWqDw8Y5+l
CRpUKpVQljRJ8lMCbNjzh+5Zr7g4qDFSNRyeKXCuSaJw8QeufoLFaTG94QUG2PTUoPEyZAhNB
S4GNooW2wQ0DPHfXRvs6umMkqF2aKzIHmQDGvz1xD+CAQTH3mFTQe0U2gXFJn9FoZ040jFB6z
Wnvb2xx8LJhGIHIw8feGDRTzJUGBmqXiOTg16huQIvumTScBotKjpgJmBmKCRpXtUGfJKionp
Az7RvnYDR1BhVvXzJXfQmtqNGg+eQgE0FSgyRCG3EZfUjiQZ0G069yaEUw/TxBgxjtujMpAmV
HpBOPTsBOZ6HGmxaof9pbu34LlLLrlP+FIIfVdX18RDbb+Kb7V0XCysUQlbHRhtu/KrSRWo2B
1kgSNAQNzBWzVLANIXnwT/u2TMQiLOpDnh5FcoVMoFa0EigkOLmdRq7dC9+R3lxbIFXIFTIwW
Wdj/TUPZARUkVTh1kAK+uR7e719xJo57d52MvkE5TSWTWNTTj1mEfuVCaoF4p6AumMog36C6S
FaB6ejZCApYgySFegC9AnYCMaZHkG+0C5tVe+eeRGJxqcKU4PMckyah3r2fRGuNVCC34ApQkR
lFpvz0n6tRSB+nHQE384Tg/XgEw9LMMspkl7FmnIPyK4Ud+DXYLXH1Bpb+mUzMTI1/bYDJP2v
W75f1/D0vNexQ3GqWISEpgbMcGF5BYfH9741Ue6K7w2mkRxzxSx0R1L2Z/MF0CzYhKAZTAJ3b
rZatNaYLxIpPCGoc6lCqj2/1AU4DAa2e++YbXyZ2i+Jh2tBUxPU99ZxM64dda9PICzBUaaAZh
rMpWnjsiZIbb3keWi8p6RZUzJRSAXWgn9QpD4kyQ7g3Vfd+zZ1v1fVoA1eJchkCXYaF1jMBqS
KDCpsc2InqK4R99yaHZjob8mAWdxz34JfK1I00j0KJwjmwESDKTcJsRfqHnuaznAcvggCZ0jS
0o74dYTeCE1CQFivtR6Rdwjp80qlGHIhoVV0mIjsONoEh1Jo8LZ7dOArMQiJCrkYkuZOJSyki
UJyhircHeLdW4Cnhx7u0ZAIkyjkoZFhDozuEd5Zkx4XaptX4iSWHNP26yaUUqvAAVXAZAYzaz
SF/bEf7FsUWXhIDf67R8pmwfQpZvfO3e+a176TfhJ3DG5Akt0yXCMaU48WB36xvVF0kylGYeE
hN+gPhe2Y/Go0veZ5dKZE9/3+zHj16BzMjYFkDmRQP6E0foOg+XWzYIAkVG+RpCPyPjQEnwuy
FPwG9BmkDtonmcBUMTMio/Tg9wVjh6Tgn8G4X3UqWhTQxkCaRkdsgGRX6qj36GqF6XnnAgg+n
oKRdOE+KFDi2arDEaR8jsGKYCRKcPrPqq9eAva4RFMvbZJWo/aHApmCWN0380/PQ++FjnzXYn
e8KRW01Pb0Jm1MBaI5UIOvpd0ub2ZBAF8o/hkkF8zcYCYgtiOKo32rIrmDDwZ9UthI2I5pHDm
7c9kLeNGG+cbrFILfYQkyj9L7DMbZxPeojxI5jUR8+k4kc8gHg38S9NljXFwZEiSj7JodAxiq
uBCl6VKx181wS9Q/ItRH5jHG/7vinAcNopi5wFwDb2wXs9LZ5cdAcKugFRwyUF6yjMfuEZtAN
szMTPas6rJUttveSCKHkDCeFKG/y1qibNVhCHvlCWaQNHYUVSVsmeR91DsrxVfgS92r8aiAVt
oFkLVHiL1CxT8T1DVMp4eXEEqa+0AAvikmELWP3TUbXWdoAa4MlYJkKtiZBG3jwKpRocvWTTx
yI+gE/NqHoDvPaPmf5mZp1DnjY3aUIpOo4ZyxWNULvlC6UPm4emrBZIJJz+EQoX9zLehM0HVg
VLhdNfbQzd01PvHIUjHTiH+0uc86dacXXHUW7Nb0OzP3QT34jeAew7bZoTE2IzvDwBrcs/tes
wyTpINL9xxvWpRUVUWJkkRbOrgswiJIxbSd1aIU3pFiyKPUHut8HDSoMCvBZAQnTzsYCbUlil
5LEiVkrMkHgAkS3jUh4vHosPOkymWg0Snjq464G41SfZDYvozE3XscQmQAdMTe0JNGfVfL0K7
fgF1KJ9l3tYtdFi6KTBXJBS0MWvjgIY7RYO2iEcJuQaJICmQEVfQCp6KvpMdwwzi1Ke6ThKrC
qoJNdX81js9owCEJjIoNcTeEwJC0N2GD2YxRkHnM8Mr7TPFw/LdGU6oj1njilDkX38tBnYQ6p
U8gFZgTauepx3CcAcQt0+kkZGj2YIfIFcoSg7JRTwFB/RYhxZDuEHLlPZkYcsxgns6bs9jOFu
qfYK9MeOgaVGCthkSPBy0DQbQLTSIxJKBZWCDaV+WNvNw7LgQCdOBrDZK7X8RFCPHTJcHe7kt
uhoTdI7cwmobYCXvaXkNkmBaKqxQ3BTsPzC/EGWjcijyAq1Fk6pFJZDhOg/2v0OQPhKK1PcI+
E1RD8IavtDU4fBmehXgTQl8rQp8a/tmc81T/iJ9Mgo0bMsaAGHsT2pROzAloGsYpUxC7U3Fht
z8BrYNGqHUPn6iFtMV8Ewm1R95KE9Sg7flC0BXB2Sbn0sWLO0WTFJlO9so3D4ncKRQlGYIYS6
E+JDlBtMVbEQIomRhMq3y+DETDtkJdKfZaQgRUf0HHpv2W1lnTrF1QfA0UCmuFNORqaBrCmiU
WoDBJLG5p+hU64trpD6kBH7bcXLPQfO+S+EdL0K209b1aq1sCxx6qzUM1s2lMlHbPuLYGTXNs
PgmhvJkN8fEW+qGj6gvwBWj0Fkuvj4bp7Sa0vSStVoLZ6rcxTVNA1IQArirSsHdhPh1QaYjky
oEZQRsxO3N8CBpiTzWYEfPI1JtY9Wb6rGKSyKjGdNUd/H0V8G/ul8i4G8dek8AndRAsdhLNpZ
cuZ+mkNzWwBqJX3sq4oq40nvruMTVHOAvBtDOH9uz77ajCZIJMJnsXD4ncu1iuCVIVUmzgCsr
OQtGW6E/Vf4tjH72qkQxGBK0U/6SYmRmcwCIKujWwDU8qnCBp8Nai1sbiEeG8aGMsJBK81zbE
0mt8qNpUZm4U5YZoNHr1XI2v6xCJVcdgjQb3ZgAqUElDY619JRHPKHR7uo7ur3BpxgGaWHQ2R
+ZzsskUEiuhWohX9R4qjQFT0mbIiRUhCREc6jbgn0BL9mIKXiOUGuldahyPQC24jYAP+fpqbf
DiJglibEjrNZGAEoJpYAJzCmlMTUZckwfaFBvZ7Tv+aTSPse+j1BlhnRECoflCMdppCD5GYYo
xYeUn2p5JoU5xa8XkL5PqqkGjc1vF1CYc6VcG7Bo1XVG8tCuj9fe3m807g2lWihXFquzoy0Nw
xiA314OTV5oadOJ9tzi0KJX//AMptuxP3ym3wMvBo1ET1lD+KaUJVY/72sFhIQqaZ5iPH8Ih8
DRCQKH/6/vvm6t644jhniGltFucqj6cpeUKtC6gLsC50F4su6sVENMYlchpW/2imaddaJZjcH
xpksF8Bot5GEddo0UB2xKqMqQMtrXcm2YlPMA0Dc6VPIc8jTksW3BPoQqu+BdrVu0pRFWkxSh
LVDOUHElzTJYhNuk0Fd9oGWGcAy29VW0IuAuhtBcV29UXjNRkqb4Y3wHusTv1jTlBeGbb7pkN
r9euJH9KSA+NMTMSNcJRJjPWd9NnAZTxdZy/fqZ1FC+MrpF2+QzXUatxEkznpB1H16oi+Jtr7
KePg4KODZEPJbk2ca9DJAKt+ZgmMs5N2m3swRM+b5JMvNZBV6Kn17CIRo+94vMJZjaT+utXNU
URY5Cj5PVxKvc0jx1ojWVBxaDWIEmUTFmG5EvIr1Gt8Zs1/mGFrouAp3QPLuDUl+fHOiTEmC8
WgeNai65W6GqNlGXQoFS76KpBc/Exx3hvWW9CjHqawGSKLBcwm1P7R+rqgUlaY0ajBcdBNTDS
sDWmMf3dImkI0TR2gmDQugoZTuUKrWvUOcT7jsk2096uw6ALhfTccKSTn06Qd7fy4ylVV1V8f
CdMMn11+Tpp7O+SoChs468PX4ptDnjsjdsr3vugJUok+gTICGd+NFJ9zwMa/3uDKzVqPUFyt5
W5pNE7R4RlZIjatCUgsX6BmGZvStHa4522VVddVBOTXp6DAjqZYN7dySGtcc+7PkbgW3WUKMs
D5y17lMor0UKLNNQt/kbtpff5rlOzYR4eBY3JBYSJaqRloF0fops2W2SzjRJlR1IfUeTamWlx
DWmr7SciocLGZILM59jZDXZyg3t6wj3cY+s67v1Lv7Hj/RGr1dzcILc36HaLfv2GKcqd2P99l
W3Qdt+u84oUFVpU6PMKvVqS3F5TuYyH1Q+Ws4LkWLy9SiTuuGPgGyIVJJlgZndIOoOyxj+tYL
WGqoplpC8jyDZVV8Pzk7tbFMtqq6y3hknW14T6YEOevla0B3Ec6qEEVyjUgq8tSo69yiHPkTR
FrB0SuWpYR96HCM+qDkcYVSVuWyFFjS00JCflppXqGmMgXKnU22BONVuKzaPsmH9rZMf1LC1B
S2IwicXEMmXS1iqkXcLqFFfWuHUVHIfE2g1iWomuNoHbayRN2V33TajLkMhHCiJWKAVKGoNbx
p6FQUik0WqVGr+37dq0GpzhQi6258jr2gnZZU2WduMo7Nm+LqR0imnIvs9Cmr5epgC2LdUefX
7GPz3h0xS5uSZ5dyvmeqnFl6+45xWZNFrL6eXu1aPvP2BvbsT9+KHy40fYpZBdvC83iAQJqZo
/fuA3W2a/fYTpb3z9+QfvriuyxEdnZiSyWFFFHe3CaebYq0XmdySLO9Ftpf7Ld+TpCeN8mO9G
Mu9gucvu9j+Pz080mD+qmiQpKDgnNE6P/vgVC+l7THonvn7WavsFa6odDUViTIviS5Bsiplfk
eRLTJZJKBdeqVYVbAvwro1GRAJhhbTQDJnNkMSGbQjvqR8etP72HXmu0RRkEpiirzQ6ZHs2b0
/5knYiNJwbbwUSwaYWm9pI3E3tweb6qHbv8ntrsHmGn2dUTyVuVSIIdUzsMQIsFwertDYwIHI
xRnxiVYruoYUQVWWCHfgidmWlRZiKCY4F1WhnDy0QIey5G5GDOznCvjYxgKiaG3s85OaYZTz2
efu6nWnBGIG6xn/7jnt8Unl3R/bxI+vJI+X9A/Pa0yz7/daCA8SLou8/YG6uxX37pub+oRtfP
/z1CN7H8G1EiBjBbDf4Pz8z+/gBufmdz9/+4HZSMk0IZk0cX5snRGSITvAyIbl6h6QT3Jcfys
MDpq5jmmooOKgj+PbhHNxFQxZakoRgS+eDM2qwtiSH5B3olOrLdzXXVzwV15SbH7y7ERJcLyg
J1E6wN3eYdBYY9GqN+/JVpayiT6VLEd7znTRmmzGoNUqSoPM55uZafj49qV9XLGrBPnUCRXqE
DZ3ENFaCwzeNEjoNDuD+ce+d160rSzY+ixq1jSCysmVKlQj1U4E4qMWTTGeY25ues238CQwlu
bVoGs9XNtJWQ87FkmIGHNxFZ1lCP45dW+K1IxK2d9nLQKQ79tiYUaI9bRlfAFFSG4CyxH/+gl
xdMb+5YZ0m/Pz6jWXtm/otvV4iZxaB21vs3Z24b99UHh4uwvd8kEDoCGa7xX/5yvTTJ27uPvL
z6x+QOybxSZtoMDax9r5SfDolefcBUcH/+RmzWkcptR8W9jp8o7rnPTZJgiSPmYLBISdgpkjy
Dq0z/I8fyMMDWjvmNzesVlt+/FzxbiZQKYhF8iuS2W1w0H67R1crpKoxnf7Q9S39973xaNQwX
A3FFlfVsFxqbQxrVXIVEumxh2CPRrVbsImNqrcNn+3Grmrvd3Txy86FjaGu7RoEJZ2liAjV/R
Y1Fm5vkDw/+Ega52gSPBYNaxckz4OaET/KMD2vYAcWoVJPRQiISY7L37eDxsljdmfy5XBI3dy
9yniPf3iAumb27g79+JGfX75y5WomyJ6mo9Mcub7C//yp8vO+JbDdft9qFKF1wWwL/NdvLH7/
JMXVrd4/fOcuFTKvQV3v6jqi0wXp+49QleiPn5htcfRJnvB2nMYyEpS1FkRwG6X6DnaaYpdLT
HqNrh3+51fMZoOIxT89k86m3N3e8vlzQaoVy9RipreYyRX6tIafD0hVYfpEcjY09rIQjMYg+c
VEv4URTNIQtcVYE23pYEe3xT2btk4KsUYQ9EV7ywU6/BsHm0ATFJRME9TnaDLHzOay+0QaE6I
Pya4dKJMcn1hs7frdjaKZG0OhnrU6EhEyDImYo4UkXg3eo6oqdtwJ+GshmBn6vMLXNYt/+x35
7RM///iTW+eZttcZ1Arc3ARnzrdv2BH7/bUEs49d99+sV/jv3/Xq7o7tesPDes07McFx1mhl0
xnZb7+hmw369Vv7zH8pqKK1I5nkiAi1gmbX2KsbTJaJ+3mvcv+AqbtyWsZ7/M97pp8+8v7DRz
7/338n+/CO+eQG//Mn8vCEabeCXzKjjfnUohjm0ARGZGYZk0Ua+cCYSNCOII+1L7Hx7oxj2q3
S5nOUGCQQDvBsIorafiCZpZBPQmXhM9aUAXqecJA8F5lM4QxCNQoTMeRiKNXzrDXPvqYk2FmN
IfKWC9mrhq0bY9+WQji/OQHMZkv9n38wn88ku73hB4oTCTY4is5myGSC/rzH/kqmdwhHEfh5T
1JWLK+veZZQ+Fmiao9NSD68D6WY/vwTW9ecmoFL5eN4C4BzGGPIs4x3v/+Dye+/Cwr1//l3la
/fAoHL4I5wWs/Pe67mc/n4+/8gv7pBn5+R+4cegb8BKG2chYkqujaBSJ1Xjf2Z2PWa9Q33mLn
ktuBWUD+H4hr1JmTC+ZIYG0wbHOILqGPZszETo9qEcL1daA9A7yCWf+p9aAxcX6HrdWf/HgHR
UCXGIBTqqfHU6jExlM/SJLnI8Eizky0PIZwY66mBTH3Y5vqrTIQRECMkqw3+63ddXi1Zr1Z82
2y4iTXW0uUCtgVmOxZY9Mq+OUMjVLAiuIdHpu9uSSc5P1cbZtYGS+f2BrEW/+dnrG9UvPFW3w
77sAC9c2RZJv/rf/5Ptd6jf35WHh9JfLCz+ypv3xvgVyt0vdab2xvxzyvVH/eXhuKfBgn0YFQ
xJtYe3GPSPc/lAMlGSmsgTh+yqVT9vnZ7imMKoB6t14idEDbwe/1ojdZblSyRRpBq9+0AvQQC
1+8PxMxn4uZzNU9PZ3pMIUNIxFJjcCi1hioyzd55OMosbMMlyJk2fPAEOAQXffUKIfjFNPGIb
/uUD/HnPcJSwrbSwyPpdMLy6opvmw25KpPZFJPn6I+fMUDncPtvgef+DDRKm0G2G5J6yXw+58
dqzUaV+XSGLBbowyNmU8TKSL/SX7CPuRFBn57Qh0ekrKJPbHeW4/O2CcymmMUcnWRh9+bpEVP
Xg1Z3ZOlZMObdFhR8IHKIgn3gyIvSslWze4dYDNTu8G80P+IIrtr7QtSjrojBMp2JKurRegvJ
hMHJviOKRsseBpNkDObuFi1LpCg413o0BGJvsqsah93u5JszCLyZKifaVZoBJLOYRHqJIb8WT
vUivkYfn1i8u+M+z/m+XvNv80Xg4pvN4P5fhfFhya5IXaObLYv5nO/mO/cok6sliXNdiS897/
m+GdQx+qiqkKIMQSpAV4Um7MV7a5H5DLm6wqUpT+s1st5ys0hgvdnD+M1GoGEHwMToM92xozX
G/4r2iHlf9RhK65cg1/gD49FatDZ4eOLiKtRVKiYdibTvnunBY5Jkkgt3t+q/fkPqY1U29mGo
iVw2Ok/YW27i2RuEvQQPbLLIYuKDDfmz7jJJfqncP4m9Cmy3WOdYXi35sl6jeY5uC6iORWn9V
fgpbLfk11dMJhOquobJJEjQquo8t78Qz/7SEiH06z3m9hZdb5GioImoCOWLEpjNMFdLNMvkab
3W+8+f2azXfPz0CakqlRfM7ekRdbIa7QKA1NchvyCq3XIseeWQivUKf2BoqwZtihFGXNUH4h8
Twr2PBoUcRXr2uQiyXIjWtfL9B+L9xQvwHPwV2jQ7L0G976sreEWtkF5PwvZB5LJj0Xlvw8mb
2QlLc2dTo71i0F/lYL1huVzyMHnAJgny8BTwFNnln0d7fim2Q+izWMFXFcZ7ZrMZdVWRALp6D
mqpytGWfgl4j3qPZJnou1utv35DEotMpkFyz2biRXh8ftafX77oer0GVebTjNl0givLUYfUS6
B7Nr0560nyQORNVqK2lx19pod8czv9XoRkc5qt3Tmx1IVaXCIJu9vczSPdL8ncx94YzO2NeFT
dtx9xn/c4Lucu5oa4m8g4PzJqBcwsIVvmIRRQm9DH8IC7uHXpj+kF0L9zvK2xtrX3Srdbkptr
WcznagGqct8vcwKDF6Hbe3uojXCsVM10OsHnEygaLeNXGBP7K1wHWJpYDMLrZluRzmZi/tf/V
DVGnCplVenzt+/6/PxEWRYYgVluuV3kzKcZSSa4TXN4wLkr7jS2HUS8vcfEQwP9yLo/6KvpNf
EWMGhf+8n12n2mvlfndL/zk2ehBfv8TnySqv/5E4piEBbZhwM+yGifd4+6daBxYLIMSG5Jpyk
2T+KXvdbVx8MH3/o8qQ66U2NOXykoWpYY5/Xu3R1Sh6SHc4tMHl+mfYpujLTxxX1oyYv3UFVM
lwtBUf3xI3p7f4XkbjSgXvt9kyAmhVivrNcbNuuVzudTttutbjYFzlVYgSwxXF3lTPOESZaQx
K3J4Mi6hH2+DDQ63kSkPQxod0gvhYvuHTym6BfoOeBikRVFRqyIfXV958uBPSGYqyvRLNX64S
f+aRUSRU7WrOoIu4/zmFz0qmAFk1vsJMVmNpaV1aG7EQ1qS0IM8n+p9Q+hmERUc3zY8pBWQ7i
sNalrqCuy6VJc+RyKPrwUNGo2TSyAKuJ8j2kcXtzjJqGidU2SJOCc+LIYWOFvJsM1hvJmWfhN
kpAv3zxG78HVaFXhvSdJLI9PT1gtmWSWdAJZOiFLDImN1VQaBt+WTdHQ7qgB9VYDIRRQiRV+V
IMj8NA8/UojZzAyVVCHmGSwG6bo0bMIR1NN9/cFCQJkOpUkS3GTZ61+/IAqhEBerjRJ208oFC
GYSUoyS0O4oMQOoZNaKoBH3TawiPAEhnPAZROuYuDje0yWoc6h2wJ9fkY325NF9/bAK1pGr7F
zcevssFJ5bL5cliLX15jpNBTsr13IPX8MGWEvUVM15qurc8qbRraF5+IFmM2Q6ytkOkWNEa9K
5ZyqhpxoawzWGLGqSJLgt1ttahhczXJMU7dKenX7FRrVUVTDqbbpJNQAcI6+eTWG2eUQynyrD
zgbI6Pq+t8Hjehs1sAObiODHpXku/vm/SbFJiQ3N2JnMy2/f8c9PYbCATJc0KMSRTvXgBpFUk
MyTbGTDJOaIcdubY5GmNWh8om6ULYD1X4B+UugnR4RzGRKYaByjvzmWpK7W/T+Qd3371i3L40
PW2dA3LeVQYjlZQvE5Tnmt0+4NJHnzVpd6UjSjOn792KmM3V//on1ITR132V0AJQu68l7dGRc
p24//KXHZRnm/R1ydSXbqtKnhween5+1KArU+1CIxxiMMSRJovl0SppkfP/xYzAC6f/p7zd7B
VxgxIXBLBbi81xZrweo7M72KV9Fd2GMUmwrbGo4SloEEdMty7/IL3kU9hhOv7bBOJy2yZu2d5
vOMsl/+w03MepWT2jlURejgxQGy0gIgfw21l5LTcitTU2n8u8SRvt0wpnk+JLBwX4o7dG6/UV
y6VgEVk/P/PnnnyxnmV5fLVhe30GW4v78PIjnPrVYWhVdh1efS+YeRe5u2ajn87//u242G1Kj
THOLLha6uP2A3N2gX79fdqgEdIvDuTezxxXFL2bI+/dsgfs//9DHxye8d2SJ4XqWMM0T0iSo3
gENxWmBc1veLYTaZVxNLbapvOBdR+Da89w0TtfqGbRSWczRzWYvKWgMjhG6ovhJjlxfI1k4FE
3rqvViB4EH+gKG/augj0lIjpHW6zX2VM8m8lEwBjNJsSYPj8JrfDaR9TXSXWL6XZtX23BMdgi
i7zKOe4C+ZhBBBN2CbSV54+y5dGsiTJCqKqpkpmSqP9GnLWbxG/7uNhDUSXUtqKxdNt9p02F/
ySia5egk58fXr6zXa2ap8NuNJUs86BNUE+TqGn//hK3qtoOzxt2TUm+xWBXQq2vk/R0PqxXfv
3+nLAsmqeHmKmMxSUht3Hbq99m8TrRbJxSxrh3s4tbWKYnoG63xmx/I4g59XsF6fVKSHR6D4m
czzKdPrKqSzSZoBmmakoiwenigKEuyfsbtXy3Nd/trU16btRYK1R1bokeI/EzOFdPsRAj1qY5
ORHSiDSTJroIV9wN91ZPYu62ExRO86y+tA9PgHk0TCaGWVhSpV/jiAZldoXmGbIvx21vsd8h1
UCHgLERCFNVsQuU92+0WI3AzF6apb9VJyhWyvBEmuVKVHD5058BY91E9CeOXKzqdIu/fcb965
suXL3hXcz013C2EPI1k5yPr7dnV4fae0ywa36o1EsqtnOxfikdIl3B7g1YlUrne1RdQoQjm5p
qtev7880+qsmCaGea5xRmDr2vmiWeahXXxtwjy/pACkfUHgMowQHxsBg4Sed/5NeqIa64L9Wt
3uPWZ2Pftr1CPKBC4xnO5DtBJ8HV2msJroV/xpFE0tFoh6RWaZqF00EmQDh9jj2Yedg+isxpV
QfKc2jmcc6SJMM2EphKqAOpLQDFpRj85Z5dd7s1Kw4DhTebMi0Fubti6mi9fvuDqmpuZ4f0Ck
sQis/chqeLAqPc/U7RcUa2+kMiJ6q0CojW6/YFMP+Jvb/Ffv+/l6h/rtd+YWEtd15RFwSw3fL
oWcht8K23pAhkGwvxqGKjj9JdRJPKGzESCWXEiOP4sdV16ql5/+kUVtQkqFlF3RHbtTHX70oM
vUV8Hh1qTyNvHdeS2fp2uS6HzSXaOFh/tvX4qofigDoec3fOUb2mikRIbcTuVvjn8ztgE7xzq
PWkKSZNi1Q0c8MqBPOKx1y3EIg1YE8d9nljq5ovIVjya5zCd8PPbV+q6ZpoKtwvIjMcnU8TOp
P75oBK1jeYgjLH9fQVkNkdnS/79/hsT4/h0bbDi92aovVOA6hk1Cfbmozjv1H35hjXJ7pVdH2
Mj9h63XrF4/0Gm06mmsiUzGkNXg8JxaKouEeov4Q1tt30OHk4I6a4QE5NT+hft93aRTb47MIV
wPIm1Sl0fGXhUwxv7zMci+5GwW6Vh7InKzkfRxSCqF2mrh8YQ1PW+06/3VPXQtI20JYKkYf9S
mkMf6vrgzaNz1Sg1hFwE6SPQqLwtQheopmKQNDqSTDgcgd720zEYPobA5E2WUamyiQk4y4kwi
RmiuAr1XlmvkefVgViKHflkE8ospag8lSg3tTAbSazqD1kEKB/wImpv3+FsGspFVeN5FqNqvw
g8PMHVtd7e3fHz22eKWpmlruNJ3eD/Mhhl2AK0ydpxImyK2OHhhn1fWAOvc7wROzYp4RArj/q
yXRDdP+3s69YRwz5h9+HkxPq9wVwC0vvbqut9u7Ep33vWHqmGuuJZyna71UQEkyZoURwZXr/q
aVRZnQ+7D4Nw3V2cjGjtVE4SeZC6IKi1SJJQlKWmJqp4TR3ql4C1eO9xMUBnktKp2L5GJJgUY
jYIpmNOPcza6jQikCbUzsUAGcHshG7tSTWA6JehuA/bdMt3aPoB/XEfsv/OFLWmqvFfvzP/cM
d6uuBh80SeGCxHyln/xUTfdmqSrnMRsJNWm+2vmF14fVyoCGKzrjN18TzeivYoCw3H4rTS/AC
rPTp3jc7oiZ5YpT3jpkHlErwVmso12qjr/a9tiqq0e98nG0sTSFN5enykbDK9jiC0l0wg4Ist
aZJgrY05zEN01WbhwrLcc7bsD67HJFKLJgmPDw84VSTLXuxDalXv5r2ANdp+JlFDazSHVh3aw
7D3oTHUcZ6tMMq7R6dSQfBQPaCrP5EU5ON7/HIejyA6vSJEBHl+xqw3XN/csHEJj2sglq5uT3
iKKeM0v92QR/F68QQfRDQe3Rs7UJMgSS79MQaNeH/MbxD8LWDS4OkWoa3sMbKID9y95zgaQFQ
CGr9cqJCjo2rJxfM60M67oAJVkHQOtUJZHka+129TAPPx8ZGyqpHJJJYyPgc0nOq+3pIYS57n
1E0l4VZlNEg6R6tatSjO1GLi2XFZhhfhYcCALhVHDdGECLwkBLa0/XT/POodJCljPpO9XkUGR
C6ydyjnkXuJhK4Yt4L1Z2CL+fABvbnh3LxJA/DwyNQYFssrvq+UojZdJaX4K01ZNteTWTu7u+
OIvgFIT4pDLBbRKeLHRvo2GR4mEWxGOFVw/OH2Jwu6Ndp+tGuPqwQO2hSy70t6ZUjkL5jU0MV
QXQ82JXg7RfJracr7nmzLWJjNWG+3ui0K1usVZCnkw2LNRxm8CFIU2LpisVhQe2Fb9ybJ5IHI
n1aYcqhqHxu+GgOTKettQVXVrFbPMMkhGS6Q3d/9tluKCvnzqlwtlyhQ+YZbSmygDuW5Rqh11
9XSHKHkYtBRYmSPyMfwGhu8aBEIvbrHfnov+vE9fsSw3sdKMEUJz8/cXl+jNuX7WvE98uivPS
FqNKG600BJHevk0PyOfT6+Pmwg6GY5mAxJZ7I3kgOM+1VE3jYpBpIsqKfGoKGI9v7FOzrxMZO
8OZNr7BoBiB7Qcbfpmfg36novUs1Ljsw/oYVTfXzg+B583MrLUjTPeHx8BKDcbnCiMJtegJoE
Z+LTM4v5nOl8wXNBOKtNknA2Ww368MDpcN6ebpQmaJ6xWq9Q9WzWa7w1MJ+/YNqiSl7V8PTM7
e2tzGdL1oXG2h2BAlRd9OKfsbyMgBicD0RuzeE1cQ564h2svuEfP6u9uRLubiPW+3Z+/0ZRD8
9rEuD6+prHwrMdC/EfMyW0p85foKqfNU4lhnE3NCWQzYYln4BjAUEXEflRP5mdNKfDdXvnYwi
f+qjhkP7IJOxK8pdCb38kTVPs9Bpz9RviDP7LF8xezvVeA6GNxYKt96yenwGY2hrjN8hsiiZ9
lf04wxAReH4mKQrev3uHZAtKncHkHdgZ+vMBU1Wc9djiroHOppTAZrNBVcmlQnSLLObhwMQTM
EYaAqGyzGajv/32CTu5YlNHHwYE51tzttc5eAo41xD58Ny+QyZcf53gCIcrRPtZvMLmHr950F
BdJj3U0nBsZQlFyXw+R0V4KuDErn3/biSq8qOErsNrD8KecEx6BC1okiPpfEwZOQiXSXIZagg
DfEyCpNMYzGaDPfoSB0S0wY9OhMQLd1JCLyf5cP/1zQ2ffvuN2eIWXZfo5y+YzfYod4Sg5vvJ
FD+f8/j0RFXXpEa4mihSPkJm0Nl0NJjoUMum9vD9J3lZ8f72HcnsA8gM/fGIPD1zds6fenySI
ssrVpsNZVFiDVxNPFI+QJ7AYtEdxHfh7Eldo1++kqzW3N68w8w/4NIbMHkwtcTEfd1xXFu1PZ
6E0xC5aTLQ+hf2CLqVmH2HWFSX+x51g6Lbp6ApZPkoFnsaonq0KALDtwmbSqkvLI0lerlEP4y
UAZvH14oai2TzcXP4CLxgC224+TOAdCqUK8VXwYZoz3Ftb+38NzsfAecReHttbGiH6Zz9SCQ4
bKhKnYug6y18+xGOER7smx/qH5w1mI/vWdcVT4+PqCo3M8NEQhFHkg3m9hb39EyiSj9z7HCzi
im26Ocv2DQNam9VIbXrHIPSO+L4AHhVuLujMhK86t5xMzXMshBdpskjcnuN32ywm21PKzqPiQ
hgK4d+/Y6ZTZjcXGPmHyWkiQrqvB70oA0aCuU5vGts8mYADIIodwuVtBiaFJIJ6mrUVSF7jJj
9bdPGJut7dA6sEwFVtKpCOqw1WldQOSHdO4LkxJCadfza8z9MGh1u4SRT0jkkh49FOgQv2ycf
JDv0P08Cp9negySoVAgX5C4r5+1vKpyzT9538uy7CATWG/z/+XdwFaKKkSZSTY7erYC3BvPbR
1ySyPfPn7WsKqap8G5GPK/b4dcPmNsl8uED/vOXwf7voWG2pKYaK+XC0Pmge3O0pxmqhkP77m
7k/suXkM1mhXdLgRiZyPYBWcwwnz7i/uP/YtvgmDELtutn35ZVzPMzulpRTyYqsxkmi2bbWEm
V3baNCRpRE6ugCrUOQikOzZNKAosPyOQ6Hjlaq7giBPrYBJPNRFcb3a2ae2h8oeHmiOywiXNh
ndCumYbQ+wVWe32folTFRrMXQKKzbSovcaO9OBgmLIcR8kmnotVGxRWIpBArXLaC55hwPFOKh
xpGjZtzd9mNtHuoHY2Rc9I/jaVP3MO7m3h0TSxyd4efzeTzn3/qarUis8LHeQii0IiWuC1+9Q
N791FcWag+PJ4ZpBH7Hoyt2U87LXF9nmM+vGe1WunPnz8xArdzQ259u8LEV+j6KzL/DfP7b/i
vX5GiOuWBGP9cwunystnCehPRbE6cP8GITSweEqnawI7cPQYGTIJ7WilPT8gkhyRFTAKVx99/
D5+7/g7JQVdvsDKyjNo5dc7RHBf+Ys/u7iM7G0yIPYman0oSpLh5Gbm+MuJtZPAmgXRGq7L7c
GL54JYxu/5cKU5DbHp4Q/WXgIIGApK7G+p8wpc//9THhwdSI7ybCfOkqeoZQFB0c49PcjV3t2
jtYfV89jiHk3WeLHKpRd7fUQCfP3/GO8diYoKfQHvUIwpug199RmafkI8f8N9/YkbqmZ+GyPL
bLKkxCT6mBwBiwtFXcd7smYJKAbSGusDYKf7xEXkOdf+02alQj1xCZTZB8pyiKHDOkZgm0Odl
0LiOLrMjCSp63BdXFNJplOIvW+9vs4XWBwVJp6I2pwt5PXXTC0BjzbOR43XfDBqrBMWLoMsl5
rdPFEnGn1++8PDwQGLg/Vy4zsf9sAYHT5/BrZH3d+hsdtG22iXgkgR5/54yTfn8+TPb7ZY8Ed
7NIbP74lFQTL1GV39A4jCfPqC3N3h7oATYKOx6mPqv5cDr7q3G8kqqwYQ/l28HAvJotUXyeAC
gV4xXjI/10c+ev/jkZlM0S3mM/pXUQvrac5guvj2BJrIRhWSK5IuR85ADCKcrw7yKyA/bNcEL
qCa4/9Wkb0qDQZBru214zvUXd4CgPhR/9pMJ8ttv8OmjPBQF//nnHzw9PZFZ4dPScpMr9sgAD
Q59/gZaIJ8+oIs5/hzn3kFQ+iJC1VOnFvn0gSrP+fL1K6v1GiOBAc2sIk678/T6W09eMdUGnr
9A9Yx5dyvy+z/wizle2EneOThZO3idA40TsXPjNoUTzwUBqLdBK5nPRt3B57WmaJLA9RWr7Zb
n52eMwDyTcOzvK+AYrxzF1uYQa92pSZHJFcNz0HauPwPeIEHlANhcSKZK+YzYvLf3McTtMr9l
7752n7xpbDcRolMTD7c/pgIr3sc01Pk0FFRcLKRyTr/8+ac+PT2h3rPIhE8Lw8T6408ytmp8i
X/6DMtPmN9/Ez/J1f34ifGO4VGQx9rqqe5xrF49fjnHfvxEqcoff/zBarXCCvy2tFxn0Xs0sh
46LVIQX6LVF1zxrGb5Afs//iG62qh/uIfnFeJdr7jlGQ6WnSu0fTccnxgb5ltDxdGLLDABiV5
1M5vCT7P79YFeGXxTiyLv76jTlG//+Z8455gmwjKPTOtSdfs02vv4KDHhJJyQomJhcgUmG+/5
AuX9VUQ+RHZnJsQg6Swc1uYAk6N+G22lYFe/Zt40Rrz5xGCcicX+pBHznMM6ROJWi0gIwTQWk
gSd5jCdoVlKUTuevn3Th4d7XF2TWeFqariZQorrnCvH+on/ja/wj3/iZ3dqbm9EZ1P1Px+QzT
ZWHvU7W2N7fnNa95RYfJ4i10tksZBVUeiXL1/YbjbkVng/F25y387TMbxaEhTFVCv05xadXKl
MrpCP78M56+s1brMN0W6+qUarLYPbVxmjljHoobcjIuCNQRPbRhzKS9ZEVNlNfoWzCdadPoK5
3UEQwacp5t0d1WTC169f2Ww2wQSbCdmhAwYugLFb9wlcgllrsvjWQDZDkunBni8pefU6SS5yX
IrZVMiXqpt7xCSINimpAQZ3NkL5HLEuhEw3A/L+PdRRS3C9kyUbj63GngamonSHM1gTcr+NwR
tDDVR1zXa7YfPjB8U2nAOdW1jMDfNUyW3P/r5Q8hhqdPUNX65UJkvM+5vgkCtKtCjRsuzGM4g
xMIg1aBpi4iXP8WnCpqp5+vJFn5+ewDuuJ4abCcwSHTgBz0ZRQHDo5ie+eMKbHJfM0GmOmc0x
ELbbnAs11J2HWOiiq1Lb26EQCVpRTEQRE+c7SRBr8GnK9uG+ZUaXqOttX9UWZu+ESa5+1eSTd
8984DFoqqnkGcznMJ+yrh0/Pn9m9fxMauD9zLDMLjE9XgMSHNQ2j55nA8kMyRbSEYTs3HHZHM
n5DpYDEIko/Ix179HiWaV4BFw4iF3rcRVIg1Z/jvdZMZBOqUzOqjI4CSma1hqMGEwk5HBYws6
9cV/WOY/zjrquqaqKsqqo6wpXO8Q7cqtMUmGaQG6VxIRIqt3hv5TRKxZNcmo7xZkpJs1JpTs6
t9VIGiIRg5dQPnq12bBardluN7i6ZpbCdS7MM40llF4HzbhUwWGoSahIqUhQm2FsSpokJEmCN
eFI6kPqcUMuXoMpVLuaqq4oyoqiKNhuwhhuJ4bfFiDDWr8nEASf5Ji7/0+0dMpmC65GXDx91M
cCnxJKPWmahAi4xFI4x8PjI09PT9RVxSyBu5kwT3XvOb94HoUQFDO2yaAE9TzJw0UKmkzDvn/
rsO4ZVdFXdCm8AZFri8rBJa+Kbn+oVGvQCq0LOPQgo0OobeXAmLpnLKxrYV1CrYLzwQT18bs2
wUyH93Y55EGCWAnlllILeSJMEiE1zcN+PdEcBsEjFE5Y1RZNJkiSY5IEG89g915xrqYqK7bFl
qIoUA3OvmkqXOUwz2kLHfwqXDXiWjphWymlFyoveDHB1DG2d/qMRoUqHIvkvMd7h4/MS1Sxoi
RGyBNlkgjLZgyDPps/0vlgGk9zZIKqimZzZLKkkgxMgjU2nr/RtaPeU9W1FmXJ89MT6/Wauq5
JBK4nwu0UUvFnzd8urcKBeRdikvx+VIlikCTa4Uooyjh7B/aAHc5LNJ23IHI4b7vFl6qbhyCq
idalCYnw0nhY1SPOoS4cOYR3wf4bHPS20zfRWWMEdBit5ONC62vrbRJFDL9s8peNxOI60qj6X
ftAyxDaN82XstPuC0FMUNVKp2xrpaxDCmet4L3ifcDVWsisYWIhT5TMBu3C76D2GjiknTRzEU
6nCmq49+C8UnvtGOygqErcqY5zbI1iTKjDnkR6NdIcotDrRyWk8NocsgmSTsFmsSBl7wGohnD
WcosvtzxvK9aFI6yYjkV7DQcmuGhaGAnMfJoKy0zIbWzrjDlsijoenCdtDYYgxUf3sARs3iZz
qUmQ6W1wWI9e/XIn1hsR+eDd2BXhn3PgfTgnzLtYp71RSxtKMyF7yRjiUfTgSrQuQ32ythDDD
h89MOODj/pV+Xrq3vgM7DsIdPuElk+YHcmudgKT61hW6RI5EP+rR4tntHjC7KRaegXNFkh+FS
hCelVsFLq9g7Pkypmw04a6OHdm5JpDC3CXE0YiKtf44iHM4UALbK4yQWXNFyGlklgrr6zQqo6
HQ8TTYAhcTxKLpimSpWAUXxXUmyd8sQ6ZeIR5DNqukIhiBUw+w0yvGC/qfYTN1QV+84hoNVTr
FbydILObbp2KHLA/43OvNmGt59dHHW2MmJ3nwptsoXXkMDIY9WhZKdsCLbbh2NzatWdztc4hB
TXQZi9ZG3Kh0wymOWb+TvCKX691f84Oj36XCBryPHZHd328RxWZ5tSTlPvHDRNbs0ibKmWC5g
skXaDb8mB1z3F8YypFNkHnU77er5lazzLTLs5dBTO5BjNBtwVNFlrXxW4wkPA6Au/jGGrXmdl
CvHPKerNTf67pedxB1B+rAmQ5Ls/4fv/MRBxXOS3DVAVvM2RyjeTLEL/+uIH1Gsoq2NnRkTqw
/SWaZUYgTWE6xcxn5Fcf0LqgWv1A6i1pW+Yl4iwGpleojSexnDVnIS1W8mu8yVnff2dqyhBo1
Gh/0wVMrkVXG+0O5RiZMyMwncnD01a9eq5ze5wYX/FI32affFeIQBh0Uag+heQFqSrENWV2Dy
wIB/RCYHUTpISfT9HJFKpa/Zev8Syw16F6Cah6+PCeejrjoYCNwNTGTEoMYlN0s4UvXxnTAI4
3DrpcYD5+kLWmut6EKLXgwY9NiaCrFXz/3tmn7C6gt4G+rwMUTRP0H/+mut3Cn3929dtj39r+
PaPt6yvccsljAU8u+BNyo6gKms6Q5XvQBL1/CnvzVbVzes2+xtCyNK/dDsXTMzqbwvU1Zvkbm
6efVOUT0yRu/Qlt9W/dFvDn53jS0CGpO+zRTyfYd+/Ibn/j8edXZj6cdtMq+7VT/+0b9kB9QF
XweQa//67P24r1eks2XXK1zAfsG4gbWC89IybAq4lcO88IzStRxT8+qn7/iSmrEU/lMZRl/5X
37UnwotrLbvorQDCqhIPvgle+X+lHRWJCRIH4uCd9gQkkgCtLjCqz2YyHnxsqTyhx3EAToqns
ZHb1/78N9HUMiGquhNNldG/uz3RI9rZam0Ucgu6iDyVfYpaf0NLhv3zGFMUF8f37+Itz6NMzf
rNGbm+YXX+Qh59Gi+1PbqcSi+cFH5CJWXAtQ91Zz/vtK7pa4+ua/NNHko//4OHbF3z5xDxRvH
NIFsObBkX6em1oCJNGwEdc2oSrHZ72GjW9gdfVeBuZEFHF39+r/vkZW5YHubz0fsc+H0ATeGF
kUIBQfvFvM0iFsI/uu+CSFg1jQRK0qfetenbbrYlTVVDXOpvNgkCqZd+sEOlNdd8efsux7kPr
zTXHl8rRtlulw4SyXpFpCUAyRxYf8Ost7t//A7vZDghczu1jBB9be+TrD/jxU2/u3kthr/nyD
J6YIae+y4hp17LutTNsPybSbAv03/8Tuym4efeRIr1h5SziaySceXzgftr1pIB34URgszu/cu
rJnA9vU8ixB/7pWfXbN+wFnPjUYpNou3clmH/lltYoBi2R9wNMQh2I4B01Z5Vu3ms13BvPRs+
nU4yxFE6HG0kaI8Vey9JfANpEqASX+ovmXZo/0p31LaLBcz5/h25K+PItFNY4MMZT/Y4xZwCD
IPcP8PCgHz59lCpd8n0T5YZ3gXkNMueGMO6QC8/CqkM/f8Y8PbG8vqVIrnmqesE/x/C1kchVR
2P2347EX52gsuN9LstA4O6MWM/LOgpPxcSNz79SW4dYoNIGT21fkiuQZAG3C4h8D30F3W5Jk0
TSLKN0UHsZXvA3EDjsSPLXTr10ueOCYOa3QAI/fr6ISe7CUA5L+4mohx8/kfVa33/4wJqcxzI
kIMklqW+DnkIf1oW2k4dHrq9vsbPrdqzHJkuaYhm+k+RvsdM1Bm8qyfXpGbMtOKfM0WUNB/sp
2Cd/9WKPzhRjQiIF3ZpQBdIJWrsQ3vmaXrZbDJDnGbWHut9cW7b21439YMu9kNSXStmuKYk2K
EzmC5J8Lnr/cPDU2EvbP3SnNNrS169kwPL6loetsK0VREStedVyNc7D/QPy8yfzfCJtQNAxxH
eI/Feu67cjclejz0/IEdXn5RC32oRIYX+tKNe4yNU3cXRRbRWDJDlSVr247ctBJNRcl7LUfDL
FeSgcnf/hiBr7yyH2K6H8Kq+jhk5df/fhA7KJ1XLeAM3TIJiywn3/znK+gGzC/cYF5585lijc
3H0cjCrm/hH3H/9XtShHiyYN2jPhqCn9ZyfyPmJaVipVNYrsJY6egxC3kuQFJ5m+FFo8g0onX
n1Hb0qoJGIStKrO9qgfvMp73GZLnuWIsRS9OmfdKa5D3P4S4uhLpQPP9hi0O36EQxTUK/P5nN
lkIv7+HnNgp+Ql4zvkgGs+FzGY5xW2qpjP55S1C0zHmNHndykOIga73aJ//ImUJW29uLGLTay
IAxhjBnTz1gT/aoppJ8K5XljR20LreIO/XqIpbVkj9YFBt6Ue00mIaijDueGXwHDXIXByXa1J
04QktZQOvMZYrBHH28HF89YgPQI3LzTKI2cMo/Esr5bodquy2RwUCi9Gd+cXhna6eA+rFbPZF
GttcOEm55VVPS2oAsMwVXn85B0BiYdGaud4a5t8a9v8DcVio1qOfvo6aL3r0jo0/rJFDm2/jT
3Z2OSSzcA5pTpeAHHQFJ2l2EGsj7bdkoiQZhmVg6rxX8Y91H71uL8CVAjHLAFtyuhLQRplzDD
NJ/in55Aa/BeDqMB2Q2YT0jTFq1exr62d3G8fTpGVEhhms55kR5K/NbyYyPuhGAqBG44geooQ
9cDv/kVNVRnZ/+rE77l9HrpXojTTWFfOSNjOk3QSVPX6nEIFp0CgrhHnyLOc2iuVa/BtGNxlY
zkE510fHY59DWJkr3z3vkNtqoSQ0CRJSIxB16uDM7Z7/1ibFz2/fssiUFZY58myDOccYsdjwl
4uRIZ37o1T6G3J0qu4E7+Wpo23EWOvkOQ6VCuMiQ6M1yC2e29vYTe2W9xf3GMoR2hMD7zeu1/
6b5p/nQbhIw4ixKNjM9Ht9kVOtzELULxHqoo8nohauEZz6dVZG10xL4VDs9EYJXTnmcU5ePnT
Dc7LfDIJEYRFOcD8qAq883qcIZ2LhiLOI3UVjoj2fidU9y3gOD7aj7uQHZv8Fwj0F42uX12pV
SCTRMizXuG/80D23nWWlLaMpLPJW+99DwmNOGnLAY/1MQ6NRaDtT6+buAi8DwcTGAGxKRiL32
zO7GEcp76UMSgUJXmakiQJWxdHo76VhAGhJgurj+/+TI6Oc/DO9Nrp2uvOJFJodpdEUGv3Wth
v80C/UXolSSJa1yG09AwVdVwmnsceDjaoitY1iY3579a+iLjGeg6fyeD9KDREzo6jTbu1+FZw
eey6tn8YvDIGWS7QS87r2rsq3OetgeksHv2roRxSmoRv8xxdLpEkFilo9m8lqLv6+BTrpV0yJ
EHnU2Q2jR/EQgTOh4y5eASxj7HpRkDSDJxitsWL7an+ko0sDC1LErMkTVOKbYkjVqMxgs5m+C
wwF7FNhowGLWpbwONju8CUc9at4o0gd7cgjYc57N3ifCDELKeqa03SVF4r8cQYTDymuCvEeQr
PhpQC+1ErIaVXTKg10LR1RksDqGvsdIqDkKr6Cpt47M7DrYXnhTEhs49973p35esSUxp402qt
Zj4XN5uonnFY4DhEAr+7w8/nlL45BC9EBPmiUDubonkWZE1DjKoYY5gaE9IGd4h8fMH3GFEs6
VstFpRl2U64kVDWyBrLZrPRsiwBCQwmm+C3hdIeL3SqvzNABCkrrCpZnrNZryidZeproMbcXl
HHkFcfk2VQZTKdik03qo+X7jkr3qbY21spqkrrum73bA2CiR7G1WrF1fX1WZJ3nL1HH0YMSxb
nBpN0eL6ab8LpJjqdItdXaJYFAvAe3azDcc5N7sC54II9rA2TFNlLivllrrA98+9AT28UH3E5
kR8T0rG4v/7xJ1J3hHbeog/1w5kvqOdzvnz7xnq9CsQ7nWKMoYr78CKGqipb4hYR8jwnv7mhq
TJzmsnsDMJYnp6f+PH9B8YIk8wS0kTC4iyqCu8qJpklzSaInaAPK2RncM309Fs/9zFJ1Eakqp
jkOQ9iWFfKLCnRp8/UJHx7dmxrH/KwJcRmv//td01slEaXqHkKYsI20o8fP3h+eiJPDamJKqe
xcS/XcHV9PXoU8VljU8K9zYI924fRZc/rdAYf3vNc1zz++IH3njzLuL6+Ik1T9I/PR3HZXbbh
8IWotdjoNP5FYaUDUGhiD7x2gTC/0rv+5nXXzXwu/t2d+i9f6R8+MeJSa//3LGs0S6i9Y7NZ4
5znw4cPXF0tRRWc8+pcTZIkuFh611qLMSYk/niPN6Ld0TgXPDQj+MpT1zXLxZzfPr0DX8XTMm
ucJvg6w4qSZbHw3na9t7DGejxXmVQlHJ9bVuSzCcYY1lWNTkFcQUbJ+1yoslA2LJzVJSTGhXK
+vYV6lh8ChSQwxbqu8a7mZp6wzDx48FQ4BTUZRrRzwl0ILUbSVCI6N8Eo4KZiYLlk7Wr++OMP
qqpimglzEXRTIte/iX+caxdxOdb/+Kfe+1aSv5U3+yREHJtS1HsZaN2Fb9Ldi4j81HSY62txt
VP/8x5zgedZENgWZMslWZZhTM3NzU0bJ5AkCGTx6mzvflWNZXcuU5g1qpHOuVAgMUmxWXPQe1
iUqXegTtXVIAatfSifPOrtvmyx7Hk4ioJ0MSdNU7abikotmQm4ZVYHIw80U4GZSygUF5jfoRn
Yk2gSQjp9PODPisfEWHlDYCaYeBzwoL7ahSM00dXhvYg0+J2aq8AMnBHIMp6eHqjrmtQK/7hJ
mCQeZYv4Ss3VEp6fBiM8hqnGZBnvHBgT5k4drw7dPQkhJkKFuCV7TIq/2PAbwAs9Kbs+xN1WD
ebuVnh3i08O70HuqrWIIJsNpii4ubnB1TXPz89nz7g0XrG2hw7bYxA81wYXI5CGnFWgOdPNTk
SyhUg6E8o6miT91ofbDrvOnHMGIiiUBVaVST6hBrYksZhhBmmKpmkoLZwkMT6hceacKx97WNu
QKOG8pym6Su+3K0T4WvswxK27utY2wOYMYgSCJ1qgrmpUleUsJc9zMBMwYUdHsuyg93/MpdXm
c/t4vvDI3OnI75tAnMcuiPPQeWZvI8lf7C491b1Yi7m9Ffn0AT/NzwzVC3uY3D+wmExYXl3x5
csXyrIcvXmPC74otj0sXjUSuDpgT0VAqaLFNlZJ6frvK6E+z9DlnHOKuMruu6qGqmYynYDCth
LUTMIxOjb4A8ROIZlCMqF9jGd6v7sFG5yIXlW996FefZKCTUMKbZKF18187FaZvASM4NRT1TW
SJJe1E9Vp50K55GmeIiZFTR7PDpPArKTd7zvRYPDQe8K2aLB7zjs4802IvYlpjyGt5uC8vg1b
eRmR9wzqo9NpDLJYiPn9d/xycQbKkZ9tN8jzMx/evxeA79+/7zGJgyrOS1RK6dS30MSJafEeL
fa3ziT+VUAXC+TmBrXJIVl/GB2vSFEwyXNEhK0z+OwaJreQX6PZFZou0WQOySwcLCmcReR7fc
fsOo1BIWKzwExMHn5tkJat82xkJ0F33o8PKvRTlWU4isp0avHR+dCdNyKk0yuY3iGzW2R6iyS
TUMNWmhv84Na99gVIk3iwRnQQ/5XHYDeSfGyf/BfAyzc+Jf45EG7ZXSeQZWJ++yT+5irUtjqF
lAe9fyDxXj9+/Mjz8zOr1Wr4uMc0g50kjrMGoXSOkMhZT0lyrSqVoqJLRxt8iyYWM58jk4nof
NqmVw6vOuKBD0UwyZKELM8pK0fpE8gWQn4lMrkWmd6IzO5EZu/FZFeRv1z2OEOAinQHDpoYqp
vMAvNIpmCnnbQ89azHoBUIQV0vyxJNEiGxgwk4yPyk8YT39pODRiPhNxcV25T7bj3Xx8ctSJJ
QlhV1TCQ5i9B6z3FXhT9bpY/Msi/Jx/t+O7/A28TznaGTSpJgP3wQvbs5j9DLCvfzJ4v5XPI8
5+EhOF1O33jJkOJjkbBZNlCfjt1VxRLBe4spbAPqbI6zCZuiUJZLRmpIj2HRtSKgZYlVZTqb4
pyjLJvCCjL8bUpiCaiRtgrpoRne0z2MDSejqiI2Q7JbZPpOmL0Tmb0X5u/Df5O8gIl24yPiVp
ZlkLOTyTnusfDXe8Rr2CpTjTsr3TUCUGxD8YaR9vY+SRI0SSjKAuddxO/YwUghfsMvFvgDtvv
u+0O2fLAmZPS+E1i/GN4+OfsYbtZi7+6ExYJTe5IiAo/PUFW6vLpivV6z3W5P3TTcjz0Xwl5U
W2/rKJGrwraI5aVHpLgIspiz2m6CmZHn4qfzk+PdGQhS12hVsZgv8N5TFEUbBjmCFIFgL5fkY
gze9RyO7dlCO4wEgso9MrdHZ7vdPwxaT1EUlFWlZrE8GIbcb1kRjPPYsmQ2m2GMYbPZDHv3Hv
f4xJgs3ScyhUlwaBbb3pwe04I0nMAqnz7Ax4+4Sb4j1y54ttGsastgDST5r1Hb/7oKDA1YC4v
5WdNi6hq/WpPnwXH3vHpuY+MPqldygXOop0oG9elA5cw+1DVst+ObP6ohGmuSswomBkVVqb29
OecIvyFq3qObLbPZTBJrTxB5HMjFjrFOkncL7sjlIzY5nKeiEktaO+dYPT9j5jPRNDvj7lCjT
Tcb5nnOfD7n6emJqqfV+dVazXpzhtM1xvhPp2yKgqqqArG1YzsGAtaKm03h4wf0+hpvm4Ss5t
7DCvtg5ppJbvMx+ve/PbwNkUv75yw8JbVBtTyqWAbw2y1JSGxgs960oYAHvfVtu2eC0qpq6o/
ZSPHyutZDRSIUYL6g8p71KgTKqHeY5UJ0MqE9DmoHxnoTBTYbrLVMplOqqqKu66Oze64DZ7DY
+nnNfXW8jcTq32jOkL7jEJ63giqbzQZNEljMObuE/nqNKUo+fPhAlmZsNxsF0LJSvb8/+xRSz
VJ0OmW1WoU995gTIeaUvyGYGz/vH/ixWqF3t/DpI346xbfE3V/Ph/BptMbgqTm23t5Krr+RTX
7h5XWoIiNNttMRkNq1C+6chd45h7opOnZDEDJD9emwJNcQADMSrw7BoWOuFtg0ld/+8Tv/63/
/b+bzhWAMMp8NfMn71vzIB2WJOMc0EnlVVUdGwsUeYmkcb8614z7awktMITo7NGT5dZ2b66tw
3vrhu7qu6xq+fyP3yv/4X/9TZvO5UNf4b98xqzXnkIT3wPUVFcpqtUJEWC6WcbmcctaF/2VZ8
O3bN9ZFgblaivm3f4i+uwsnu0ZCHxNeg9GIxOPnT/tq3gLeKKx1RKqVpWpVYxIL1oYQb+9Vtw
V8/8GJ5UQ7SWnSVrVsssOOYiLNJJ+jIHdqrsZkj1ilYxw5r0FVHxM/qpCloEq63WriPaw3cH+
vbltC2Wy5NQsh3haxGLYYu69rdLPRyTRkx223WxaLxRFT5bRm1EM4mjYGFxOBBlJlLDlCevb5
pdBsUXaF65A8E7m9Vv/tR+tB793Q4Rlfm6LC/cd/IIuFGmPwMXBKBtcfGK0qfj7F3tzIw7dvW
pUl+WTCfLGIGs2xrVdta36FtditQ0kS7Pv3otOp+u8/kO324OkvrbyP6+C4d/3t4I0PPOxAyw
r/9SuiiiaJIqAuFEUwzh95Jt2yVwEznVI4h6vrNlXxODLD0sGnnEIKYENur1clOSbJnYeiPNB
vzK76zz+iVhDiv0U1qEutdjG+lPcQExCn6HpNensbQ1y38TidkfioXiBQ6+sab7l7EdRzcbWL
BWlPza2EMm3jVsdBaI6pbuzfZmErBlku0dU6MMTxTvv9Y71HHx4AifN6DJFmZSo+S7Ef3rMuC
n14eEDEcHV1RZbFs8AbX85BGdIx5jhtA7xksRCyTPX+AX18DCmwB5vq6s+PYfvW8GaOtz31M0
3CoilLzGqDrDYh9/pkXa+Og/ssQ+Yz2W421M6RpinW2uPLa6c++Dl7l9qT5IdyewG0jhVpW0x
7LYsEE6SuEecxPjL/1s69RMoCGgjBrzdYhSzP2RZb6ro+vGF56T52xMvHM7uOjb25/qi/4lhf
pgs2GlQmTVPh9gbfFlM8reGJmKH/4ChGGjzjd7e4JOHrly8hwWU25erqqsWl0wAP9NqGou6Po
b0my8S8fyfy6RM6m0RbfYh7vDlyyr9Gkr8Zke8NJ1aKIQZRnB7GUDx4MZi7G7wxPD48oqrtFk
rsoddvb9FctJcbPavWHiyPO7i6KIM/YaQdP8nR2TScub7nfAlVSjlSNWfEwg/zVhSYmHrqnGO
73R4ezgHv99HrJVa8kS5//BBGre168ZoMan7YwdA9KWgWC5F373Byrpl1PngRuL5CY/ryarUi
SRLu7u46KQ6n/Rmys8YOgTHIYh4I/Sas324dRK9MK8lPIP9GtP9G3vUeN2oQMxay/CDBjSuuQ
U31KHp9hbm+kc+fP+t6E7bRlsvlYIJH5+jCdQ6ATQbFJw7CZjOo56YtoxGYTeH9uxgs0d97Vb
x3+HyCX8z3UhqPu8sJdcmLLXmeh9TT9frI9d0W2skpENqqOq45Ulo6BtdN85Agx57nWdNtjoQ
Ni2Bub8T84zdcQxRnr5tDoDj16PU1vHsnX3/84P7+HhHh7u6O5XI5dL20GuCBLbCeJD8ofVuF
TZA8F/vpo/DpIy5Jg/nW+77pRsZoBxAOJa1cDm+bTy7SOVYEJEtRY3qBIycIFMWLRW+v4OaGb
9+/6/39PcYYrq+vyfNc+teONiIyWtzgiKkVTrOog+f6IJF7H4Jgdm9GUWsgyzHTmbiba9WfD/
E5Kj7PkZtrzHIpWlWq//kHUg2xOYhbo7JvC9LpNNR922zaOPOxsbc4HWqzDzG8sn8eV9u1jqz
5ZoHuonmqn8YGP5EbIMuliBh13771HGoX9hWv8dbC3S1cX8v3+3u9/3kPwM3NDXd3d/u+1SMa
ShcX37985OI9dVYw11eik1z912/Iah126ntzMbi999GFbo+j8OZFIwYQUyLVxbJJgy97XmYRN
LGhpttyicsn3N/f8+P7dwCurq64ubmRk44hQIyIN1Y1HnN8dKJUURIk7hUfk+S+rNQ7h9ieza
9B9SLL0DShrEpNb2/xq3WQ+MsF3NxQeGXz+KiL2ZRkOsX7w+WI98FC7UI99jRjtXqmKEudTCb
7TRgJDOeMxlUJtdJU2+Nzx+uM9UGCaWNsxwBOUaIQ4w8IiTC76vruEBZzUWtUHx7R9QapKlB/
woPebE4KmiTodIJcX1GlKfffv+vPnz9B4Ob6hk+fPsloboIJhSobx2Z4tpFlekWNDb3rCXV9B
CTPxf7+G/7HT9XHp47Ie9L8V8KbEnl47h37lzQV7m5ViyIcDO91WPpHTMiHTlMky6gTy7ooeP
z6hefnZ4yxvLu55jZ6l88Ca0Nhwnp51uQZgDSRuqr0GJGLNWI+vNOBJIuLXKylUPj+5Qv/+Mc
/RG5vFYF6MuXh6YmHhwe88yS//8by9hadzy7wGwQ1mlABB+89m82ayWSyf2GeCx8+HFBxdkCD
plU5p7WrscYM6n+3L/vSXAS5uUbn88tMfwVNUqlj4cJjwR8KyHQqkmXotlA2G9hu8GUFzgXm2
Zd4kTglSZHJBGZTfJqw2hbcf/vGZrNpbfDr6+txAicQIu/fD+auxVIVk2U477S/3XgRWIu8ux
WZ5EqaonXdSvXxmXg7eHNJLtJzKBiDWS5lk1i1xpJYK32JoarUda1FWbJ6fmK9WlPG2m2LxYK
7uzum06mYS4I8xODzXB6LQt2ZVVvr1bM+Pj4Bofj/qOc0TVlby3qzH3ihMYprtVqRZbl+fP9O
NtutfvnyhfVqhVfP+/fvmc1mIknCytW6Xq1HzYpDUD4+8vz8hKpSHTiCR9KUTVWxWq3OalOLL
ev1GuccSWIxdp/B9V2IKrRze1ayULxTEMrVsz49BfzHCK2T1HHxWItOc6kSq8n1ldgQE9sdxw
WB6VgTiNxaKZ3Tp+dnHr99a8OAl8sl7969YzqdHgx/ABCbsk1rVqtVVwa8/5yrssmfIE3TF0l
fMRa7WIhzjsfv37X11F/c0mXwC9T1/rIIHK8qa74+fMM5p41a3Owle6dtQbsszbhaLrm6vmY+
n488lDHHyP5nJu57P7flgE5gLMJ0MiXLM66urg7eIMaw2WwZYx7GGOaLeVD9gef1iufVE0mS8
m+//dugXWMNm+26DdE9iV+0CSeTCWmacnt7dxBHYwxFjMs+3W4Y03K5ZLFYMJlMO+EVv++7Po
ToI/A+MBI9bfu3T0eEyWRClmVcX18P8B9sqfX6M8ZijJfn9Upd7TGJJUkSTNoVXqzrmmK9Yr1
a63q1xqvHGMNsNmsdbCcnIiJqjFBst5Rxm3T3aFIxhsViwWKx2PEPXQAiOO+1rKqA53SKTZK9
tt5Sg5c3O1ytq2UT3w7b9d5T17U654K32Wvr3THGkNgEmySSnDx8rtGRo719xkJ7EzjseO1Bx
/2dc6xWK82yjFH7+UXwlu6YfrOHvdm/CvrOp8GOyahDSinLQrfbgjIyMOd9PPo37opYQ5al5P
mE6XTKJJ/IIU3prEf5Kjjdg3OOoiw1z7JRE+It7fRfQOThz+vaPW8xd2p/c8+/4L8KHIxFOGP
d+IbAe0yijb0/kziCIvBryL3bZHopUz6RDXghvKG6HiesEbS8ZvqOj3BUif/17PnF8JoF/d8V
DnnZ93ftmuiwDsw54c3nwC9YMyL7+P7d8Gu30CKcPZcnLjycmLHrCfirYBzh86VJT02F4Ubp/
7PQn7vGAfYLezqwZ/2i9va2JC4Rx7219MaW0/8PSL9HchZQmhAAAAAASUVORK5CYII=";
const DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday",
"Thursday", "Friday", "Saturday"];
// ---- BACKEND API HELPERS ---------------------------------------------
---
// Everything (orders, schedule, settings) is read from and written to
the
// Google Sheet through the Apps Script Web App at SHEET_WEBHOOK_URL.
// This makes the app work the same way whether it's opened inside Claude
// or hosted on your own domain.
async function apiGet(action) {
if (!SHEET_WEBHOOK_URL) throw new Error("No backend URL configured");
const res = await fetch(`${SHEET_WEBHOOK_URL}?action=${action}`);
const data = await res.json();
if (data.result !== "success") throw new Error(data.message || "Request
failed");
return data;
}
async function apiPost(payload) {
if (!SHEET_WEBHOOK_URL) throw new Error("No backend URL configured");
const res = await fetch(SHEET_WEBHOOK_URL, {
method: "POST",
headers: { "Content-Type": "text/plain;charset=utf-8" },
body: JSON.stringify(payload),
});
const data = await res.json();
if (data.result !== "success") throw new Error(data.message || "Request
failed");
return data;
}
// Starting schedule ‚Äî editable later from the Staff > Schedule tab.
const DEFAULT_SLOTS = [
{ id: "slot-thu", dayOfWeek: 4, location: "Sunshine", time: "6:00 PM",
active: true, lat: -37.786194, lng: 144.835139 },
{ id: "slot-fri", dayOfWeek: 5, location: "Fitzroy", time: "6:00 PM",
active: true, lat: -37.800667, lng: 144.979222 },
{ id: "slot-sat-1", dayOfWeek: 6, location: "Footscray", time: "12:00
PM", active: true, lat: -37.796083, lng: 144.894667 },
{ id: "slot-sat-2", dayOfWeek: 6, location: "Essendon", time: "6:00
PM", active: true, lat: -37.748694, lng: 144.911639 },
];
function mapsLink(slot) {
if (slot && slot.lat != null && slot.lng != null && slot.lat !== "" &&
slot.lng !== "") {
return
`https://www.google.com/maps/search/?api=1&query=${slot.lat},${slot.lng}`
;
}
return null;
}
const PRODUCTS = [
{ id: "special", name: "Special Hot Dog", price: 22 },
{ id: "double", name: "Double Special Hot Dog", price: 24 },
];
const DRINKS = [
{ id: "coke-classic", name: "Coca Cola Classic 375ml (Can)", price: 3
},
{ id: "sprite-lemonade", name: "Sprite Lemonade 375ml (Can)", price: 3
},
{ id: "solo", name: "Solo 375ml (Can)", price: 3 },
];
const ALL_PRODUCTS = [...PRODUCTS, ...DRINKS];
function findProduct(id) {
return ALL_PRODUCTS.find((p) => p.id === id);
}
function isHotDog(id) {
return PRODUCTS.some((p) => p.id === id);
}
const TOPPINGS = [
{ id: "pineapple-sauce", name: "Special Pineapple Sauce", price: 2 },
{ id: "pink-sauce", name: "Special Pink Sauce", price: 2 },
{ id: "ketchup", name: "Ketchup", price: 1.8 },
{ id: "mayo", name: "Mayonnaise", price: 1.8 },
{ id: "mustard", name: "Mustard", price: 1.8 },
{ id: "pineapple-pieces", name: "Pineapple Pieces", price: 2.5 },
{ id: "quail-eggs", name: "Quail Eggs (3 units)", price: 4 },
{ id: "onion", name: "Onion", price: 0 },
];
const STEPS = ["Day", "Food", "Extras", "Confirm"];
// ---- HELPERS ---------------------------------------------------------
--
function nextUpcomingDates(slots, closedDates) {
// Returns the next available pickup dates (must be at least tomorrow).
const results = [];
const now = new Date();
const tomorrow = new Date(now);
tomorrow.setDate(tomorrow.getDate() + 1);
tomorrow.setHours(0, 0, 0, 0);
const activeSlots = (slots || []).filter((s) => s.active !== false);
for (let i = 0; i < 28 && results.length < 6; i++) {
const d = new Date(tomorrow);
d.setDate(tomorrow.getDate() + i);
const dow = d.getDay(); // 0 Sun ... 6 Sat
const dateKey = d.toISOString().slice(0, 10);
if ((closedDates || []).includes(dateKey)) continue;
const matches = activeSlots.filter((s) => s.dayOfWeek === dow);
matches.forEach((s) => {
results.push({ ...s, dayName: DAY_NAMES[s.dayOfWeek], date: new
Date(d) });
});
}
return results;
}
function formatDate(d) {
return d.toLocaleDateString("en-AU", { weekday: "short", day:
"numeric", month: "short" });
}
function formatGroupDate(iso) {
const d = new Date(iso);
return d.toLocaleDateString("en-AU", { weekday: "long", day: "numeric",
month: "short", year: "numeric" });
}
function money(n) {
return `$${n.toFixed(2)}`;
}
// ---- MAIN COMPONENT --------------------------------------------------
---
export default function DogsStationOrder() {
const [view, setView] = useState("order"); // "order" | "staff"
const [staffTab, setStaffTab] = useState("orders"); // "orders" |
"schedule" | "settings"
const [staffUnlocked, setStaffUnlocked] = useState(false);
const [pinInput, setPinInput] = useState("");
const [pinError, setPinError] = useState("");
const [orders, setOrders] = useState([]);
const [ordersLoading, setOrdersLoading] = useState(false);
const [ordersError, setOrdersError] = useState("");
const [scheduleSlots, setScheduleSlots] = useState(DEFAULT_SLOTS);
const [closedDates, setClosedDates] = useState([]);
const [newClosedDate, setNewClosedDate] = useState("");
const [scheduleSaving, setScheduleSaving] = useState(false);
const [scheduleSaveMsg, setScheduleSaveMsg] = useState("");
const [whatsappNumber, setWhatsappNumber] =
useState(DEFAULT_WHATSAPP_NUMBER);
const [whatsappInput, setWhatsappInput] =
useState(DEFAULT_WHATSAPP_NUMBER);
const [paymentInfo, setPaymentInfo] = useState({ accountName: "", bsb:
"", accountNumber: "", payId: "" });
const [settingsSaving, setSettingsSaving] = useState(false);
const [settingsSaveMsg, setSettingsSaveMsg] = useState("");
const [step, setStep] = useState(0);
const [slot, setSlot] = useState(null);
const [cartItems, setCartItems] = useState([]);
const [customerName, setCustomerName] = useState("");
const [customerEmail, setCustomerEmail] = useState("");
const [customerPhone, setCustomerPhone] = useState("");
const [notes, setNotes] = useState("");
const [submitting, setSubmitting] = useState(false);
const [submitted, setSubmitted] = useState(false);
const [orderId, setOrderId] = useState(null);
const [saveIssue, setSaveIssue] = useState(false);
const [error, setError] = useState("");
const upcoming = useMemo(
() => nextUpcomingDates(scheduleSlots, closedDates),
[scheduleSlots, closedDates]
);
const groupedOrders = useMemo(() => {
const groups = {};
orders.forEach((o) => {
const key = `${o.pickupDate}|${o.location}|${o.pickupTime}`;
if (!groups[key]) {
groups[key] = {
key,
pickupDate: o.pickupDate,
day: o.day,
location: o.location,
pickupTime: o.pickupTime,
orders: [],
};
}
});
groups[key].orders.push(o);
return Object.values(groups).sort(
(a, b) => new Date(a.pickupDate) - new Date(b.pickupDate)
);
}, [orders]);
useEffect(() => {
const link = document.createElement("style");
link.innerHTML = `@import
url('https://fonts.googleapis.com/css2?family=Anton&family=Archivo:wght@4
00;500;600;700&display=swap');`;
document.head.appendChild(link);
return () => document.head.removeChild(link);
}, []);
useEffect(() => {
loadSchedule();
loadSettings();
}, []);
async function loadSettings() {
try {
const res = await apiGet("settings");
if (res.data && res.data.whatsappNumber) {
setWhatsappNumber(res.data.whatsappNumber);
setWhatsappInput(res.data.whatsappNumber);
}
if (res.data && res.data.payment) {
setPaymentInfo({
accountName: res.data.payment.accountName || "",
bsb: res.data.payment.bsb || "",
accountNumber: res.data.payment.accountNumber || "",
payId: res.data.payment.payId || "",
});
}
} catch (e) {
// no saved settings yet ‚Äî keep defaults
}
function updatePaymentField(field, value) {
setPaymentInfo((prev) => ({ ...prev, [field]: value }));
}
}
async function saveSettings() {
setSettingsSaving(true);
setSettingsSaveMsg("");
try {
const cleaned = whatsappInput.replace(/[^\d]/g, "");
await apiPost({ action: "saveSettings", whatsappNumber: cleaned,
payment: paymentInfo });
setWhatsappNumber(cleaned);
setWhatsappInput(cleaned);
setSettingsSaveMsg("Saved ‚úì");
setTimeout(() => setSettingsSaveMsg(""), 2500);
} catch (e) {
setSettingsSaveMsg("Couldn't save. Try again.");
} finally {
setSettingsSaving(false);
}
}
async function loadSchedule() {
try {
const res = await apiGet("schedule");
if (res.data) {
if (res.data.slots && res.data.slots.length)
setScheduleSlots(res.data.slots);
if (res.data.closedDates) setClosedDates(res.data.closedDates);
}
} catch (e) {
// no saved schedule yet ‚Äî keep defaults
}
}
async function saveScheduleChanges() {
setScheduleSaving(true);
setScheduleSaveMsg("");
try {
await apiPost({ action: "saveSchedule", slots: scheduleSlots,
closedDates });
setScheduleSaveMsg("Saved ‚úì");
setTimeout(() => setScheduleSaveMsg(""), 2500);
} catch (e) {
setScheduleSaveMsg("Couldn't save. Try again.");
} finally {
setScheduleSaving(false);
}
}
function updateSlot(id, field, value) {
setScheduleSlots((prev) => prev.map((s) => (s.id === id ? { ...s,
[field]: value } : s)));
}
function addSlot() {
setScheduleSlots((prev) => [
...prev,
{ id: `slot-${Date.now()}`, dayOfWeek: 4, location: "", time: "6:00
PM", active: true, lat: "", lng: "" },
]);
function removeSlot(id) {
setScheduleSlots((prev) => prev.filter((s) => s.id !== id));
}
}
function addClosedDate() {
if (!newClosedDate) return;
setClosedDates((prev) => (prev.includes(newClosedDate) ? prev :
[...prev, newClosedDate].sort()));
setNewClosedDate("");
}
function removeClosedDate(d) {
setClosedDates((prev) => prev.filter((x) => x !== d));
}
function itemToppingsTotal(item) {
return TOPPINGS.reduce((sum, t) => sum + (item.toppings[t.id] || 0) *
t.price, 0);
}
const itemsTotal = cartItems.reduce((sum, item) => {
const product = findProduct(item.productId);
return sum + (product ? product.price : 0);
}, 0);
const toppingsTotal = cartItems.reduce((sum, item) => sum +
itemToppingsTotal(item), 0);
const total = itemsTotal + toppingsTotal;
const itemCount = cartItems.length;
const canProceed = [
!!slot,
cartItems.length > 0,
true,
customerName.trim().length > 0 &&
customerEmail.trim().includes("@") &&
customerPhone.trim().length > 0,
][step];
function addCartItem(productId) {
setCartItems((prev) => [
...prev,
{ id: `item-${Date.now()}-${Math.random().toString(36).slice(2,
6)}`, productId, toppings: {} },
]);
function removeCartItem(id) {
setCartItems((prev) => prev.filter((item) => item.id !== id));
}
}
function changeItemToppingQty(itemId, toppingId, delta) {
setCartItems((prev) =>
prev.map((item) => {
if (item.id !== itemId) return item;
const current = item.toppings[toppingId] || 0;
const next = Math.max(0, current + delta);
return { ...item, toppings: { ...item.toppings, [toppingId]: next
} };
})
);
}
async function submitOrder() {
setSubmitting(true);
setError("");
try {
const id = `${Date.now()}-${Math.random().toString(36).slice(2,
7)}`;
const order = {
id,
customerName: customerName.trim(),
customerEmail: customerEmail.trim(),
customerPhone: customerPhone.trim(),
day: slot.dayName,
location: slot.location,
pickupTime: slot.time,
pickupDate: slot.date.toISOString(),
items: cartItems.map((item) => {
const product = findProduct(item.productId);
return {
name: product.name,
price: product.price,
toppings: TOPPINGS.filter((t) => item.toppings[t.id] >
0).map((t) => ({
name: t.name,
qty: item.toppings[t.id],
price: t.price,
})),
};
}),
notes: notes.trim(),
total,
createdAt: new Date().toISOString(),
status: "pending_payment",
};
let saveWarning = false;
try {
await apiPost({ action: "createOrder", order });
} catch (apiErr) {
// Don't block the customer's order confirmation if the sheet
sync
// fails ‚Äî they still get confirmed and told to send their
receipt.
saveWarning = true;
}
setOrderId(id);
setSaveIssue(saveWarning);
setSubmitted(true);
} catch (e) {
again.");
} finally {
setSubmitting(false);
setError("Something went wrong preparing your order. Please try
}
}
async function loadOrders() {
setOrdersLoading(true);
setOrdersError("");
try {
const res = await apiGet("orders");
const loaded = (res.orders || []).sort(
(a, b) => new Date(a.pickupDate) - new Date(b.pickupDate)
);
setOrders(loaded);
} catch (e) {
} finally {
setOrdersLoading(false);
setOrdersError("Couldn't load orders. Try refreshing.");
}
}
async function markStatus(order, status) {
try {
await apiPost({ action: "updateOrderStatus", id: order.id, status
});
setOrders((prev) => prev.map((o) => (o.id === order.id ? { ...o,
status } : o)));
} catch (e) {
setOrdersError("Couldn't update that order. Try again.");
}
}
function checkPin() {
if (pinInput === STAFF_PIN) {
setStaffUnlocked(true);
setPinError("");
loadOrders();
} else {
setPinError("Wrong code, try again.");
}
}
function resetOrder() {
setStep(0);
setSlot(null);
setCartItems([]);
setNotes("");
setCustomerName("");
setCustomerEmail("");
setCustomerPhone("");
setSubmitted(false);
setOrderId(null);
setSaveIssue(false);
}
const waMessage = slot
? encodeURIComponent(
`Hi Dog's Station! Order confirmation.\nName:
${customerName}\nEmail: ${customerEmail}\nPhone:
${customerPhone}\nPickup: ${slot.dayName} (${slot.location}) at
${slot.time}\n${cartItems
.map((item, idx) => {
const product = findProduct(item.productId);
const tops = TOPPINGS.filter((t) => item.toppings[t.id] > 0)
.map((t) => (item.toppings[t.id] > 1 ?
`${item.toppings[t.id]}x ${t.name}` : t.name))
.join(", ");
return `${idx + 1}. ${product.name}${tops ? " - " + tops :
""}`;
})
.join(
"\n"
)}${notes.trim() ? `\nNote: ${notes.trim()}` : ""}\nTotal:
${money(total)}\n(Receipt attached)`
)
: "";
const waLink = whatsappNumber
? `https://wa.me/${whatsappNumber}?text=${waMessage}`
: null;
const isIOS = typeof navigator !== "undefined" &&
/iPad|iPhone|iPod/.test(navigator.userAgent);
const smsLink = whatsappNumber
? `sms:${whatsappNumber}${isIOS ? "&" : "?"}body=${waMessage}`
: null;
return (
<div style={styles.page}>
<style>{`
* { box-sizing: border-box; }
button { font-family: inherit; cursor: pointer; }
input { font-family: inherit; }
a { color: inherit; text-decoration: none; }
`}</style>
<div style={styles.shell}>
{/* Header */}
<div style={styles.header}>
<img src={LOGO_URL} alt="Dog's Station" style={styles.logoImg}
/>
<div style={{ flex: 1 }}>
<div style={styles.tagline}>Order ahead pop-up</div>
</div>
<button
style={styles.staffLink}
onClick={() => setView(view === "order" ? "staff" : "order")}
>
{view === "order" ? "Staff" : "‚Üê Orders"}
</button>
</div>
{view === "staff" ? (
!staffUnlocked ? (
<div style={styles.pinScreen}>
<h2 style={styles.h2}>Staff access</h2>
<p style={styles.helper}>Enter the code to see incoming
orders.</p>
<input
type="password"
inputMode="numeric"
value={pinInput}
onChange={(e) => setPinInput(e.target.value)}
onKeyDown={(e) => e.key === "Enter" && checkPin()}
style={styles.input}
placeholder="Code"
/>
{pinError && <div
style={styles.errorText}>{pinError}</div>}
<button style={styles.nextBtnStatic} onClick={checkPin}>
Unlock
</button>
</div>
) : (
<div style={styles.content}>
<div style={styles.staffTabs}>
<button
style={{
...styles.staffTabBtn,
...(staffTab === "orders" ? styles.staffTabBtnActive
: {}),
}}
onClick={() => setStaffTab("orders")}
>
Orders
</button>
<button
style={{
...styles.staffTabBtn,
...(staffTab === "schedule" ?
styles.staffTabBtnActive : {}),
}}
onClick={() => setStaffTab("schedule")}
>
Schedule
</button>
<button
style={{
...styles.staffTabBtn,
...(staffTab === "settings" ?
styles.staffTabBtnActive : {}),
}}
onClick={() => setStaffTab("settings")}
>
Settings
</button>
</div>
{staffTab === "orders" ? (
<>
<div style={styles.staffHeaderRow}>
<h2 style={styles.h2}>Incoming orders</h2>
<button style={styles.refreshBtn} onClick={loadOrders}
disabled={ordersLoading}>
{ordersLoading ? "‚Ä¶" : "Refresh"}
</button>
</div>
{ordersError && <div
style={styles.errorText}>{ordersError}</div>}
{!ordersLoading && orders.length === 0 && (
<p style={styles.helper}>No orders yet.</p>
)}
<div style={styles.groupList}>
{groupedOrders.map((group) => {
const groupHotDogs = group.orders.reduce((sum, o) =>
sum + o.items.length, 0);
const groupRevenue = group.orders.reduce((sum, o) =>
sum + o.total, 0);
return (
<div key={group.key} style={styles.groupBlock}>
<div style={styles.groupHeader}>
<div>
<div
style={styles.groupDate}>{formatGroupDate(group.pickupDate)}</div>
<div style={styles.groupSlot}>{group.location}
¬∑ {group.pickupTime}</div>
</div>
<div style={styles.groupStats}>
<div>{group.orders.length}
order{group.orders.length !== 1 ? "s" : ""}</div>
<div>{groupHotDogs} hot dog{groupHotDogs !== 1
? "s" : ""}</div>
<div style={{ fontWeight: 700
}}>{money(groupRevenue)}</div>
</div>
</div>
<div style={styles.orderList}>
{group.orders.map((o) => (
<div key={o.id} style={styles.orderCard}>
<div style={styles.orderCardTop}>
<div>
<div
style={styles.orderName}>{o.customerName}</div>
{(o.customerEmail || o.customerPhone) &&
(
<div style={styles.orderContact}>
{o.customerEmail}{o.customerEmail &&
o.customerPhone ? " ¬∑ " : ""}{o.customerPhone}
</div>
)}
</div>
<div
style={{
...styles.statusBadge,
background: o.status === "confirmed" ?
"#FFCC00" : "#E5B234",
}}
>
{o.status === "confirmed" ? "Paid" :
"Awaiting"}
</div>
</div>
<div style={styles.divider} />
{o.items.map((it, i) => (
<div key={i} style={{ marginBottom:
it.toppings && it.toppings.length ? 6 : 0 }}>
<div style={styles.reviewLine}>
{i + 1}. {it.name}
</div>
{it.toppings && it.toppings.length > 0 &&
(
<div style={{ ...styles.reviewLine,
color: "#8A6D00", paddingLeft: 12, fontSize: 12 }}>
+ {it.toppings.map((t) => (t.qty > 1
? `${t.qty}x ${t.name}` : t.name)).join(", ")}
</div>
)}
</div>
))}
{o.notes && (
<div style={styles.noteFlag}>‚ö†
{o.notes}</div>
)}
<div style={styles.divider} />
<div style={{ ...styles.reviewLine,
fontWeight: 700 }}>
Total {money(o.total)}
</div>
{o.status !== "confirmed" && (
<button style={styles.confirmBtn}
onClick={() => markStatus(o, "confirmed")}>
Mark as paid
</button>
)}
</div>
))}
</div>
</div>
);
})}
</div>
</>
<>
) : staffTab === "schedule" ? (
<h2 style={styles.h2}>Store schedule</h2>
<p style={styles.helper}>
Add, edit, or turn off pickup slots. Customers only
ever see active slots.
</p>
<div style={styles.scheduleList}>
{scheduleSlots.map((s) => (
<div key={s.id} style={styles.scheduleCard}>
<div style={styles.scheduleRow}>
<select
value={s.dayOfWeek}
onChange={(e) => updateSlot(s.id,
"dayOfWeek", Number(e.target.value))}
style={styles.scheduleSelect}
>
{DAY_NAMES.map((d, i) => (
<option key={i} value={i}>{d}</option>
))}
</select>
<button
style={{
...styles.toggleBtn,
background: s.active !== false ? "#FFCC00"
color: s.active !== false ? "#2B2B2B" :
: "#B8AD91",
"#fff",
s.active === false)}
}}
onClick={() => updateSlot(s.id, "active",
e.target.value)}
e.target.value)}
>
{s.active !== false ? "Open" : "Closed"}
</button>
</div>
<input
value={s.location}
onChange={(e) => updateSlot(s.id, "location",
placeholder="Location"
style={styles.input}
/>
<input
value={s.time}
onChange={(e) => updateSlot(s.id, "time",
placeholder="Time e.g. 6:00 PM"
style={styles.input}
/>
<div style={styles.coordRow}>
<input
value={s.lat ?? ""}
onChange={(e) => updateSlot(s.id, "lat",
e.target.value === "" ? "" : Number(e.target.value))}
placeholder="Latitude e.g. -37.7862"
style={{ ...styles.input, marginBottom: 0 }}
/>
<input
value={s.lng ?? ""}
onChange={(e) => updateSlot(s.id, "lng",
e.target.value === "" ? "" : Number(e.target.value))}
placeholder="Longitude e.g. 144.8351"
style={{ ...styles.input, marginBottom: 0 }}
/>
</div>
{mapsLink(s) && (
<a href={mapsLink(s)} target="_blank"
rel="noopener noreferrer" style={styles.mapLink}>
 üìç Preview on map
</a>
)}
<button style={styles.deleteBtn} onClick={() =>
removeSlot(s.id)}>
Remove slot
</button>
</div>
))}
</div>
<button style={styles.addSlotBtn} onClick={addSlot}>
+ Add pickup slot
</button>
<h2 style={{ ...styles.h2, marginTop: 24 }}>Closed
dates</h2>
<p style={styles.helper}>Block off a specific date
(holidays, etc.) even if it falls on a normally open day.</p>
<div style={styles.closedDateAddRow}>
<input
type="date"
value={newClosedDate}
onChange={(e) => setNewClosedDate(e.target.value)}
style={{ ...styles.input, marginBottom: 0, flex: 1
}}
/>
<button style={styles.refreshBtn}
onClick={addClosedDate}>Add</button>
</div>
{closedDates.length > 0 && (
<div style={styles.closedDateList}>
{closedDates.map((d) => (
<div key={d} style={styles.closedDateRow}>
<span>{d}</span>
<button style={styles.deleteBtnSmall}
onClick={() => removeClosedDate(d)}>Remove</button>
</div>
))}
</div>
)}
<button
style={{ ...styles.nextBtnStatic, marginTop: 20 }}
onClick={saveScheduleChanges}
disabled={scheduleSaving}
>
{scheduleSaving ? "Saving‚Ä¶" : "Save schedule"}
</button>
{scheduleSaveMsg && <div
style={styles.scheduleSaveMsg}>{scheduleSaveMsg}</div>}
</>
) : (
<>
<h2 style={styles.h2}>Settings</h2>
<p style={styles.helper}>
Edit anytime ‚Äî changes apply immediately, no code
needed.
</p>
<div style={styles.notesLabel}>WhatsApp number for
receipts</div>
<input
type="tel"
value={whatsappInput}
onChange={(e) => setWhatsappInput(e.target.value)}
placeholder="e.g. 61416379260"
style={styles.input}
/>
<p style={{ ...styles.helper, marginTop: -8 }}>
Country code + number, no + or spaces (we'll clean it
up automatically).
</p>
<div style={{ ...styles.notesLabel, marginTop: 20
}}>Payment details</div>
<p style={{ ...styles.helper, marginTop: -4 }}>
Shown to customers after they place an order, so they
know where to send payment.
</p>
<input
value={paymentInfo.accountName}
onChange={(e) => updatePaymentField("accountName",
e.target.value)}
placeholder="Account name"
style={styles.input}
/>
<input
value={paymentInfo.bsb}
onChange={(e) => updatePaymentField("bsb",
e.target.value)}
placeholder="BSB"
style={styles.input}
/>
<input
value={paymentInfo.accountNumber}
onChange={(e) => updatePaymentField("accountNumber",
e.target.value)}
placeholder="Account number"
style={styles.input}
/>
e.target.value)}
<input
value={paymentInfo.payId}
onChange={(e) => updatePaymentField("payId",
placeholder="PayID (phone, email, or ABN)"
style={styles.input}
/>
<button
style={styles.nextBtnStatic}
onClick={saveSettings}
disabled={settingsSaving}
>
{settingsSaving ? "Saving‚Ä¶" : "Save settings"}
</button>
{settingsSaveMsg && <div
style={styles.scheduleSaveMsg}>{settingsSaveMsg}</div>}
</>
)}
</div>
)
) : !submitted ? (
<>
{/* Step indicator */}
<div style={styles.stepsRow}>
{STEPS.map((s, i) => (
<div key={s} style={styles.stepItem}>
<div
style={{
...styles.stepDot,
background: i < step ? "#FFCC00" : i === step ?
"#FF3131" : "#EAE0CB",
color: i < step ? "#2B2B2B" : i === step ?
"#FBF3E4" : "#9C8F72",
}}
>
{i < step ? "‚úì" : i + 1}
</div>
<div style={{ ...styles.stepLabel, color: i === step ?
"#221F1F" : "#9C8F72" }}>{s}</div>
</div>
))}
</div>
{/* Content */}
<div style={styles.content}>
{step === 0 && (
<div>
<h2 style={styles.h2}>When do you want to pick up?</h2>
<p style={styles.helper}>Orders must be placed at least
one day ahead ‚Äî same-day pickup isn't available.</p>
<div style={styles.slotList}>
{upcoming.length === 0 && (
<p style={styles.helper}>No pickup dates available
right now ‚Äî check back soon.</p>
)}
{upcoming.map((s, idx) => (
<div
key={idx}
onClick={() => setSlot(s)}
style={{
...styles.slotCard,
borderColor: slot && slot.id === s.id &&
slot.date.getTime() === s.date.getTime() ? "#FF3131" : "#EAE0CB",
background: slot && slot.id === s.id &&
slot.date.getTime() === s.date.getTime() ? "#FDEDE7" : "#FFFFFF",
}}
>
<div
style={styles.slotDate}>{formatDate(s.date)}</div>
<div style={styles.slotDetail}>{s.location} ¬∑
{s.time}</div>
{mapsLink(s) && (
<a
href={mapsLink(s)}
target="_blank"
rel="noopener noreferrer"
onClick={(e) => e.stopPropagation()}
style={styles.mapLink}
>
 üìç View pickup spot on map
</a>
)}
</div>
))}
</div>
</div>
)}
{step === 1 && (
<div>
<h2 style={styles.h2}>Pick your hot dogs & drinks</h2>
<p style={styles.helper}>Tap "Add" for each item you
want ‚Äî you'll customize each hot dog's extras next.</p>
<div style={styles.productList}>
{PRODUCTS.map((p) => (
<div key={p.id} style={styles.productRow}>
<div>
<div style={styles.productName}>{p.name}</div>
<div
style={styles.productPrice}>{money(p.price)}</div>
</div>
<button style={styles.addItemBtn} onClick={() =>
addCartItem(p.id)}>
+ Add
</button>
</div>
))}
</div>
<div style={{ ...styles.notesLabel, marginTop: 20,
marginBottom: 8 }}>Drinks</div>
<div style={styles.productList}>
{DRINKS.map((d) => (
<div key={d.id} style={styles.productRow}>
<div>
<div style={styles.productName}>{d.name}</div>
<div
style={styles.productPrice}>{money(d.price)}</div>
</div>
<button style={styles.addItemBtn} onClick={() =>
addCartItem(d.id)}>
+ Add
</button>
</div>
))}
</div>
({cartItems.length})</div>
{cartItems.length > 0 && (
<div style={styles.cartSection}>
<div style={styles.notesLabel}>Your order
<div style={styles.cartList}>
{cartItems.map((item, idx) => {
const product = findProduct(item.productId);
return (
<div key={item.id}
style={styles.cartLineRow}>
<span>{idx + 1}. {product.name}</span>
<button style={styles.removeLineBtn}
onClick={() => removeCartItem(item.id)}>
Remove
</button>
</div>
);
})}
</div>
</div>
)}
</div>
)}
{step === 2 && (
<div>
<h2 style={styles.h2}>Customize each hot dog</h2>
<p style={styles.helper}>Choose extras for each one ‚Äî
so we know exactly which hot dog gets what.</p>
{cartItems.every((item) => !isHotDog(item.productId))
&& (
<p style={styles.helper}>No hot dogs in your order
‚Äî drinks don't need extras, just hit Next.</p>
)}
{cartItems.map((item, idx) => {
const product = findProduct(item.productId);
if (!isHotDog(item.productId)) return null;
return (
<div key={item.id} style={styles.itemExtrasCard}>
<div style={styles.itemExtrasTitle}>{idx + 1}.
{product.name}</div>
<div style={styles.toppingList}>
{TOPPINGS.map((t) => {
const q = item.toppings[t.id] || 0;
return (
<div
"#EAE0CB",
"#FFFFFF",
key={t.id}
style={{
...styles.toppingRow,
borderColor: q > 0 ? "#FFCC00" :
background: q > 0 ? "#FFF7D6" :
}}
>
<span
style={styles.toppingName}>{t.name}</span>
<span
style={styles.toppingPrice}>{t.price === 0 ? "Free" :
`+${money(t.price)}`}</span>
<div style={styles.toppingQtyControl}>
<button
style={styles.qtyBtnSmall}
onClick={() =>
changeItemToppingQty(item.id, t.id, -1)}
>
style={styles.qtyValueSmall}>{q}</span>
‚àí
</button>
<span
<button
style={styles.qtyBtnSmall}
onClick={() =>
changeItemToppingQty(item.id, t.id, 1)}
>
+
</button>
</div>
</div>
);
})}
</div>
</div>
know?
spice‚Ä¶"
);
})}
<div style={styles.notesSection}>
<label style={styles.notesLabel}>
Allergies, dislikes, or anything else we should
</label>
<textarea
value={notes}
onChange={(e) => setNotes(e.target.value)}
placeholder="e.g. allergic to nuts, keep it low
style={styles.textarea}
rows={3}
/>
</div>
</div>
)}
{step === 3 && (
<div>
<h2 style={styles.h2}>Review your order</h2>
<input
placeholder="Your name"
value={customerName}
onChange={(e) => setCustomerName(e.target.value)}
style={styles.input}
/>
<input
type="email"
placeholder="Email"
value={customerEmail}
onChange={(e) => setCustomerEmail(e.target.value)}
style={styles.input}
/>
<input
type="tel"
placeholder="Phone number"
value={customerPhone}
onChange={(e) => setCustomerPhone(e.target.value)}
style={styles.input}
/>
<div style={styles.reviewBox}>
<div style={styles.reviewLine}>
<strong>{slot.dayName}</strong> ¬∑ {slot.location}
¬∑ {slot.time}
</div>
<div style={styles.divider} />
{cartItems.map((item, idx) => {
const product = findProduct(item.productId);
const itemTops = TOPPINGS.filter((t) =>
item.toppings[t.id]);
const lineTotal = product.price +
itemToppingsTotal(item);
return (
<div key={item.id} style={{ marginBottom: 8 }}>
<div style={styles.reviewLine}>
{idx + 1}. {product.name} <span style={{
float: "right" }}>{money(lineTotal)}</span>
</div>
{itemTops.length > 0 && (
<div style={{ ...styles.reviewLine, color:
"#8A6D00", paddingLeft: 12, fontSize: 13 }}>
+ {itemTops.map((t) => (item.toppings[t.id]
> 1 ? `${item.toppings[t.id]}x ${t.name}` : t.name)).join(", ")}
</div>
)}
</div>
"#FF3131" }}>
);
})}
{notes.trim() && (
<div style={{ ...styles.reviewLine, color:
Note: {notes.trim()}
</div>
)}
<div style={styles.divider} />
<div style={{ ...styles.reviewLine, fontWeight: 700
}}>
Total <span style={{ float: "right"
}}>{money(total)}</span>
</div>
</div>
<div style={styles.payNote}>
Pay by card at pickup confirmation, then send your
receipt on WhatsApp ‚Äî that's how we confirm your order.
</div>
{error && <div style={styles.errorText}>{error}</div>}
</div>
)}
</div>
{/* Sticky ticket footer */}
<div style={styles.ticketFooter}>
<div style={styles.perforation} />
<div style={styles.ticketRow}>
<div>
<div style={styles.ticketTotalLabel}>{itemCount}
item{itemCount !== 1 ? "s" : ""}</div>
<div style={styles.ticketTotal}>{money(total)}</div>
</div>
<div style={{ display: "flex", gap: 8 }}>
{step > 0 && (
<button style={styles.backBtn} onClick={() =>
setStep((s) => s - 1)}>
Back
</button>
)}
{step < 3 ? (
<button
disabled={!canProceed}
style={{ ...styles.nextBtn, opacity: canProceed ? 1
: 0.4 }}
onClick={() => setStep((s) => s + 1)}
>
Next
</button>
) : (
<button
disabled={!canProceed || submitting}
style={{ ...styles.nextBtn, opacity: canProceed &&
!submitting ? 1 : 0.4 }}
onClick={submitOrder}
{submitting ? "Saving‚Ä¶" : "Place order"}
</button>
>
)}
</div>
</div>
</div>
</>
) : (
<div style={styles.confirmScreen}>
<div style={styles.confirmStamp}>ORDER RECEIVED</div>
<h2 style={styles.h2}>Thanks, {customerName.split("
")[0]}!</h2>
<p style={styles.helper}>
Your order is on hold for <strong>{slot.dayName}</strong>
at <strong>{slot.location}</strong> ({slot.time}).
Order ref: <code>{orderId.slice(0, 8)}</code>
</p>
<a
{mapsLink(slot) && (
href={mapsLink(slot)}
target="_blank"
rel="noopener noreferrer"
style={{ ...styles.mapLink, marginBottom: 10 }}
>
 üìç View pickup spot on map
</a>
)}
{saveIssue && (
<div style={styles.saveWarning}>
Your order is confirmed, but we had trouble syncing it to
our system automatically ‚Äî
please still send your receipt so we can add it manually.
</div>
)}
<div style={styles.reviewBox}>
<div style={{ ...styles.reviewLine, fontWeight: 700 }}>
Total due {money(total)}
</div>
</div>
{(paymentInfo.accountName || paymentInfo.bsb ||
paymentInfo.accountNumber || paymentInfo.payId) && (
<div style={styles.paymentBox}>
<div style={styles.paymentTitle}>Pay by bank
transfer</div>
{paymentInfo.accountName && (
<div style={styles.paymentLine}>
<span>Account name</span>
<strong>{paymentInfo.accountName}</strong>
</div>
)}
{paymentInfo.bsb && (
<div style={styles.paymentLine}>
<span>BSB</span>
<strong>{paymentInfo.bsb}</strong>
</div>
)}
{paymentInfo.accountNumber && (
<div style={styles.paymentLine}>
<span>Account number</span>
<strong>{paymentInfo.accountNumber}</strong>
</div>
)}
{paymentInfo.payId && (
<div style={styles.paymentLine}>
<span>PayID</span>
<strong>{paymentInfo.payId}</strong>
</div>
)}
<div style={styles.paymentRefNote}>
Please use <strong>{orderId.slice(0, 8)}</strong> as
your payment reference.
</div>
</div>
)}
<p style={styles.payNote}>
1. Pay using the details above.<br />
2. Send your receipt screenshot to us via WhatsApp or Text
Message to confirm.
</p>
{waLink && smsLink ? (
<div style={styles.confirmChoiceRow}>
<a href={waLink} target="_blank" rel="noopener
noreferrer" style={styles.waBtn}>
WhatsApp
</a>
<a href={smsLink} style={styles.smsBtn}>
Text Message
</a>
</div>
) : (
<div style={styles.waPending}>
Contact number coming soon ‚Äî we'll share it here once
it's set up.
</div>
)}
<button style={styles.newOrderBtn} onClick={resetOrder}>
Start a new order
</button>
</div>
)}
</div>
</div>
);
}
// ---- STYLES ----------------------------------------------------------
----
const styles = {
page: {
minHeight: "100vh",
background: "#E5B234",
display: "flex",
justifyContent: "center",
fontFamily: "'Archivo', sans-serif",
color: "#2B2B2B",
padding: "0",
},
shell: {
width: "100%",
maxWidth: 480,
minHeight: "100vh",
background: "#FFFFFF",
display: "flex",
flexDirection: "column",
position: "relative",
},
header: {
display: "flex",
alignItems: "center",
gap: 12,
padding: "18px 20px 16px",
borderBottom: "3px solid #FF3131",
},
logoImg: {
height: 44,
width: "auto",
flexShrink: 0,
},
tagline: {
fontSize: 12,
color: "#8A7B5C",
marginTop: 2,
},
stepsRow: {
display: "flex",
justifyContent: "space-between",
padding: "16px 24px 8px",
},
stepItem: {
display: "flex",
flexDirection: "column",
alignItems: "center",
gap: 6,
flex: 1,
},
stepDot: {
width: 26,
height: 26,
borderRadius: "50%",
display: "flex",
alignItems: "center",
justifyContent: "center",
fontSize: 12,
fontWeight: 700,
},
stepLabel: {
fontSize: 11,
fontWeight: 600,
},
content: {
flex: 1,
padding: "16px 20px 140px",
overflowY: "auto",
},
h2: {
fontFamily: "'Anton', sans-serif",
fontSize: 22,
fontWeight: 400,
letterSpacing: 0.3,
marginBottom: 6,
},
helper: {
fontSize: 13,
color: "#8A7B5C",
marginBottom: 16,
lineHeight: 1.4,
},
slotList: {
display: "flex",
flexDirection: "column",
gap: 10,
},
slotCard: {
border: "2px solid #EAE0CB",
borderRadius: 10,
padding: "14px 16px",
textAlign: "left",
background: "#fff",
cursor: "pointer",
},
mapLink: {
display: "inline-block",
marginTop: 8,
fontSize: 12,
fontWeight: 600,
color: "#FF3131",
textDecoration: "none",
},
coordRow: {
display: "flex",
gap: 8,
marginTop: 8,
},
slotDate: {
fontWeight: 700,
fontSize: 15,
},
slotDetail: {
fontSize: 13,
color: "#8A7B5C",
marginTop: 2,
},
productList: {
display: "flex",
flexDirection: "column",
gap: 12,
},
productRow: {
display: "flex",
justifyContent: "space-between",
alignItems: "center",
border: "2px solid #EAE0CB",
borderRadius: 10,
padding: "14px 16px",
background: "#fff",
},
productName: {
fontWeight: 700,
fontSize: 15,
},
productPrice: {
fontSize: 13,
color: "#8A7B5C",
marginTop: 2,
},
qtyControl: {
display: "flex",
alignItems: "center",
gap: 12,
},
qtyBtn: {
width: 30,
height: 30,
borderRadius: "50%",
border: "2px solid #221F1F",
background: "#fff",
fontSize: 16,
fontWeight: 700,
lineHeight: 1,
},
qtyValue: {
minWidth: 18,
textAlign: "center",
fontWeight: 700,
},
addItemBtn: {
padding: "10px 16px",
borderRadius: 20,
border: "none",
background: "#FF3131",
color: "#FBF3E4",
fontWeight: 700,
fontSize: 13,
flexShrink: 0,
},
cartSection: {
marginTop: 18,
},
cartList: {
display: "flex",
flexDirection: "column",
gap: 8,
marginTop: 8,
},
cartLineRow: {
display: "flex",
justifyContent: "space-between",
alignItems: "center",
padding: "10px 14px",
background: "#fff",
border: "2px solid #EAE0CB",
borderRadius: 10,
fontSize: 14,
fontWeight: 600,
},
removeLineBtn: {
background: "none",
border: "none",
color: "#FF3131",
fontSize: 12,
fontWeight: 700,
},
itemExtrasCard: {
border: "2px solid #EAE0CB",
borderRadius: 10,
padding: "14px",
marginBottom: 14,
background: "#fff",
},
itemExtrasTitle: {
fontWeight: 700,
fontSize: 14,
marginBottom: 10,
},
toppingList: {
display: "flex",
flexDirection: "column",
gap: 8,
},
toppingRow: {
display: "flex",
alignItems: "center",
gap: 10,
border: "2px solid #EAE0CB",
borderRadius: 10,
padding: "10px 12px",
textAlign: "left",
},
toppingQtyControl: {
display: "flex",
alignItems: "center",
gap: 8,
flexShrink: 0,
},
qtyBtnSmall: {
width: 24,
height: 24,
borderRadius: "50%",
border: "2px solid #221F1F",
background: "#fff",
fontSize: 13,
fontWeight: 700,
lineHeight: 1,
padding: 0,
},
qtyValueSmall: {
minWidth: 14,
textAlign: "center",
fontWeight: 700,
fontSize: 13,
},
toppingCheck: {
width: 18,
height: 18,
borderRadius: 4,
border: "2px solid #FFCC00",
display: "flex",
alignItems: "center",
justifyContent: "center",
fontSize: 12,
color: "#8A6D00",
fontWeight: 700,
flexShrink: 0,
},
toppingName: {
flex: 1,
fontSize: 14,
fontWeight: 500,
},
toppingPrice: {
fontSize: 13,
color: "#8A7B5C",
},
notesSection: {
marginTop: 18,
},
notesLabel: {
display: "block",
fontSize: 13,
fontWeight: 600,
color: "#221F1F",
marginBottom: 8,
},
textarea: {
width: "100%",
padding: "12px 14px",
borderRadius: 10,
border: "2px solid #EAE0CB",
fontSize: 14,
background: "#fff",
resize: "vertical",
fontFamily: "'Archivo', sans-serif",
},
noteFlag: {
background: "#FDEDE7",
color: "#FF3131",
fontSize: 13,
fontWeight: 600,
padding: "8px 10px",
borderRadius: 8,
marginTop: 6,
},
input: {
width: "100%",
padding: "12px 14px",
borderRadius: 10,
border: "2px solid #EAE0CB",
fontSize: 15,
marginBottom: 14,
background: "#fff",
},
reviewBox: {
border: "2px solid #EAE0CB",
borderRadius: 10,
padding: "14px 16px",
background: "#fff",
marginBottom: 12,
},
reviewLine: {
fontSize: 14,
padding: "4px 0",
},
divider: {
borderTop: "1px dashed #D8CBB0",
margin: "6px 0",
},
payNote: {
fontSize: 13,
color: "#8A7B5C",
lineHeight: 1.5,
},
paymentBox: {
border: "2px solid #FFCC00",
background: "#FFFBEB",
borderRadius: 10,
padding: "14px 16px",
marginBottom: 12,
},
paymentTitle: {
fontWeight: 700,
fontSize: 14,
marginBottom: 8,
},
paymentLine: {
display: "flex",
justifyContent: "space-between",
fontSize: 13,
padding: "4px 0",
},
paymentRefNote: {
fontSize: 12,
color: "#8A6D00",
marginTop: 8,
paddingTop: 8,
borderTop: "1px dashed #E8D98A",
},
errorText: {
color: "#FF3131",
fontSize: 13,
marginTop: 8,
},
ticketFooter: {
position: "sticky",
bottom: 0,
background: "#221F1F",
},
perforation: {
height: 10,
backgroundImage: "radial-gradient(circle at 10px 0, #FFFFFF 6px,
transparent 7px)",
backgroundSize: "20px 10px",
backgroundRepeat: "repeat-x",
},
ticketRow: {
display: "flex",
justifyContent: "space-between",
alignItems: "center",
padding: "14px 20px 20px",
},
ticketTotalLabel: {
fontSize: 11,
color: "#B8AD91",
},
ticketTotal: {
fontFamily: "'Anton', sans-serif",
fontSize: 20,
color: "#FBF3E4",
},
backBtn: {
padding: "12px 18px",
borderRadius: 8,
border: "2px solid #4A4642",
background: "transparent",
color: "#FBF3E4",
fontWeight: 600,
fontSize: 14,
},
nextBtn: {
padding: "12px 22px",
borderRadius: 8,
border: "none",
background: "#FF3131",
color: "#FBF3E4",
fontWeight: 700,
fontSize: 14,
},
confirmScreen: {
padding: "24px 20px 40px",
display: "flex",
flexDirection: "column",
gap: 4,
},
confirmStamp: {
alignSelf: "flex-start",
background: "#FFCC00",
color: "#2B2B2B",
fontWeight: 700,
fontSize: 11,
letterSpacing: 1,
padding: "4px 10px",
borderRadius: 6,
marginBottom: 12,
transform: "rotate(-2deg)",
},
confirmChoiceRow: {
display: "flex",
gap: 10,
marginTop: 12,
},
waBtn: {
flex: 1,
display: "block",
textAlign: "center",
background: "#25D366",
color: "#fff",
fontWeight: 700,
padding: "14px",
borderRadius: 10,
textDecoration: "none",
},
smsBtn: {
flex: 1,
display: "block",
textAlign: "center",
background: "#FF3131",
color: "#fff",
fontWeight: 700,
padding: "14px",
borderRadius: 10,
textDecoration: "none",
},
waPending: {
background: "#F0EADA",
color: "#8A7B5C",
fontSize: 13,
padding: "14px",
borderRadius: 10,
marginTop: 12,
textAlign: "center",
},
saveWarning: {
background: "#FDEDE7",
color: "#8A3A26",
fontSize: 13,
padding: "12px 14px",
borderRadius: 10,
marginTop: 4,
lineHeight: 1.4,
},
newOrderBtn: {
marginTop: 20,
background: "none",
border: "none",
color: "#8A7B5C",
textDecoration: "underline",
fontSize: 13,
alignSelf: "center",
},
staffLink: {
background: "none",
border: "1px solid #D8CBB0",
color: "#8A7B5C",
fontSize: 11,
fontWeight: 600,
padding: "6px 10px",
borderRadius: 20,
flexShrink: 0,
},
pinScreen: {
padding: "24px 20px",
},
nextBtnStatic: {
padding: "12px 22px",
borderRadius: 8,
border: "none",
background: "#FF3131",
color: "#FBF3E4",
fontWeight: 700,
fontSize: 14,
width: "100%",
},
staffHeaderRow: {
display: "flex",
justifyContent: "space-between",
alignItems: "center",
marginBottom: 8,
},
refreshBtn: {
background: "none",
border: "1px solid #D8CBB0",
color: "#8A7B5C",
fontSize: 12,
fontWeight: 600,
padding: "6px 12px",
borderRadius: 20,
},
orderList: {
display: "flex",
flexDirection: "column",
gap: 12,
},
groupList: {
display: "flex",
flexDirection: "column",
gap: 20,
},
groupBlock: {
display: "flex",
flexDirection: "column",
gap: 10,
},
groupHeader: {
display: "flex",
justifyContent: "space-between",
alignItems: "flex-start",
background: "#221F1F",
color: "#FBF3E4",
borderRadius: 10,
padding: "12px 14px",
},
groupDate: {
fontFamily: "'Anton', sans-serif",
fontSize: 15,
letterSpacing: 0.3,
},
groupSlot: {
fontSize: 12,
color: "#B8AD91",
marginTop: 2,
},
groupStats: {
textAlign: "right",
fontSize: 11,
color: "#B8AD91",
lineHeight: 1.5,
},
orderCard: {
border: "2px solid #EAE0CB",
borderRadius: 10,
padding: "14px 16px",
background: "#fff",
},
orderCardTop: {
display: "flex",
justifyContent: "space-between",
alignItems: "flex-start",
},
orderName: {
fontWeight: 700,
fontSize: 15,
},
orderSlot: {
fontSize: 12,
color: "#8A7B5C",
marginTop: 2,
},
statusBadge: {
color: "#2B2B2B",
fontSize: 10,
fontWeight: 700,
padding: "4px 8px",
borderRadius: 12,
letterSpacing: 0.5,
},
confirmBtn: {
marginTop: 10,
width: "100%",
padding: "10px",
borderRadius: 8,
border: "none",
background: "#FFCC00",
color: "#2B2B2B",
fontWeight: 700,
fontSize: 13,
},
orderContact: {
fontSize: 11,
color: "#8A7B5C",
marginTop: 2,
},
staffTabs: {
display: "flex",
gap: 8,
marginBottom: 16,
},
staffTabBtn: {
flex: 1,
padding: "10px",
borderRadius: 8,
border: "2px solid #EAE0CB",
background: "#fff",
color: "#8A7B5C",
fontWeight: 700,
fontSize: 13,
},
staffTabBtnActive: {
background: "#221F1F",
borderColor: "#221F1F",
color: "#FBF3E4",
},
scheduleList: {
display: "flex",
flexDirection: "column",
gap: 12,
},
scheduleCard: {
border: "2px solid #EAE0CB",
borderRadius: 10,
padding: "14px",
background: "#fff",
},
scheduleRow: {
display: "flex",
gap: 8,
marginBottom: 10,
},
scheduleSelect: {
flex: 1,
padding: "10px",
borderRadius: 8,
border: "2px solid #EAE0CB",
fontSize: 14,
background: "#fff",
fontFamily: "'Archivo', sans-serif",
},
toggleBtn: {
padding: "10px 14px",
borderRadius: 8,
border: "none",
color: "#fff",
fontWeight: 700,
fontSize: 12,
flexShrink: 0,
},
deleteBtn: {
marginTop: 4,
width: "100%",
padding: "8px",
borderRadius: 8,
border: "1px solid #FF3131",
background: "none",
color: "#FF3131",
fontWeight: 600,
fontSize: 12,
},
deleteBtnSmall: {
padding: "4px 10px",
borderRadius: 6,
border: "1px solid #FF3131",
background: "none",
color: "#FF3131",
fontWeight: 600,
fontSize: 11,
},
addSlotBtn: {
marginTop: 12,
width: "100%",
padding: "12px",
borderRadius: 8,
border: "2px dashed #D8CBB0",
background: "none",
color: "#8A7B5C",
fontWeight: 700,
fontSize: 13,
},
closedDateAddRow: {
display: "flex",
gap: 8,
marginTop: 4,
},
closedDateList: {
marginTop: 10,
display: "flex",
flexDirection: "column",
gap: 6,
},
closedDateRow: {
display: "flex",
justifyContent: "space-between",
alignItems: "center",
padding: "8px 12px",
background: "#fff",
border: "1px solid #EAE0CB",
borderRadius: 8,
fontSize: 13,
},
scheduleSaveMsg: {
marginTop: 10,
fontSize: 13,
color: "#8A6D00",
fontWeight: 600,
textAlign: "center",
},
};
